#!/bin/sh

APP_LINUX_NAME=""
APP_LINUX_VERSION=""
APP_LINUX_BUILD_VERSION=""

CAKEWALLET="cakewallet"
CAKEWALLET_FLATPAK="cakewallet-flatpak"

TYPES=($CAKEWALLET $CAKEWALLET_FLATPAK)
APP_LINUX_TYPE=$1

if ! [[ " ${TYPES[*]} " =~ " ${APP_LINUX_TYPE} " ]]; then
    echo ${TYPES[*]}
    echo ${APP_LINUX_TYPE}
    exit 1
fi

CAKEWALLET_NAME="Cake Wallet"
CAKEWALLET_VERSION="1.4.1"
CAKEWALLET_BUILD_NUMBER=14

case $APP_LINUX_TYPE in
    $CAKEWALLET)
		APP_LINUX_NAME=$CAKEWALLET_NAME
		APP_LINUX_VERSION=$CAKEWALLET_VERSION
		APP_LINUX_BUILD_NUMBER=$CAKEWALLET_BUILD_NUMBER;;
    $CAKEWALLET_FLATPAK)
		APP_LINUX_NAME=$CAKEWALLET_NAME
		APP_LINUX_VERSION=$CAKEWALLET_VERSION
		APP_LINUX_BUILD_NUMBER=$CAKEWALLET_BUILD_NUMBER;;
esac

export APP_LINUX_TYPE
export APP_LINUX_NAME
export APP_LINUX_VERSION
export APP_LINUX_BUILD_NUMBER
