#!/bin/fish

set APP_LINUX_NAME ""
set APP_LINUX_VERSION ""
set APP_LINUX_BUILD_VERSION ""

set CAKEWALLET "cakewallet"
set CAKEWALLET_FLATPAK "cakewallet-flatpak"

set TYPES $CAKEWALLET $CAKEWALLET_FLATPAK
set APP_LINUX_TYPE $argv[1]

if not contains $APP_LINUX_TYPE $TYPES
    echo "Wrong app type."
    exit 1
end

set CAKEWALLET_NAME "Cake Wallet"
set CAKEWALLET_VERSION "1.4.0"
set CAKEWALLET_BUILD_NUMBER 13

switch $APP_LINUX_TYPE
    case $CAKEWALLET
        set APP_LINUX_NAME $CAKEWALLET_NAME
        set APP_LINUX_VERSION $CAKEWALLET_VERSION
        set APP_LINUX_BUILD_NUMBER $CAKEWALLET_BUILD_NUMBER
    case $CAKEWALLET_FLATPAK
        set APP_LINUX_NAME $CAKEWALLET_NAME
        set APP_LINUX_VERSION $CAKEWALLET_VERSION
        set APP_LINUX_BUILD_NUMBER $CAKEWALLET_BUILD_NUMBER
end

set -x APP_LINUX_TYPE $APP_LINUX_TYPE
set -x APP_LINUX_NAME $APP_LINUX_NAME
set -x APP_LINUX_VERSION $APP_LINUX_VERSION
set -x APP_LINUX_BUILD_NUMBER $APP_LINUX_BUILD_NUMBER
