#!/bin/sh

export LINUX_SCRIPTS_DIR=`pwd`
export CW_ROOT=${LINUX_SCRIPTS_DIR}/../..
export EXTERNAL_DIR=${CW_ROOT}/cw_shared_external/ios/External
export EXTERNAL_LINUX_DIR=${EXTERNAL_DIR}/linux
export EXTERNAL_LINUX_SOURCE_DIR=${EXTERNAL_LINUX_DIR}/sources
export EXTERNAL_LINUX_LIB_DIR=${EXTERNAL_LINUX_DIR}/lib
export EXTERNAL_LINUX_INCLUDE_DIR=${EXTERNAL_LINUX_DIR}/include

mkdir -p $EXTERNAL_LINUX_LIB_DIR
mkdir -p $EXTERNAL_LINUX_INCLUDE_DIR
mkdir -p $EXTERNAL_LINUX_SOURCE_DIR
