// create offset wallets for T address rotation.
// Each address is considered one time use, if it receives less than 15000 zatoshi balance will be essentially burned.
//
// This class takes address index as constructor, and will create 10 addresses by default, if any of the addresses gets used
// it will be moved out of the pool
//
// T addresses are generated by creating new wallets with an extra seed word (or appending to "passphrase") the following
// :tgen:${CRC32(seed)}
// It is highly unlikely for users to create a wallet with that specific last word and add index to it
// We could leverage other fields such as native account index alone, but users may want to set that in future
// This solution is rather simple and if standard would get estabilished for this purpose it can be easily
// turned off and replaced with proper solution.

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:cw_core/pathForWallet.dart';
import 'package:cw_core/sync_status.dart';
import 'package:cw_core/transaction_direction.dart';
import 'package:cw_core/utils/print_verbose.dart';
import 'package:cw_core/wallet_type.dart';
import 'package:cw_zcash/src/util/crc32.dart';
import 'package:cw_zcash/src/zcash_wallet.dart';
import 'package:cw_zcash/src/zcash_wallet_service.dart';
import 'package:cw_zcash/src/zkool_compat.dart';
import 'package:cw_zcash/src/zkooltx.dart';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;
import 'package:zkool/src/rust/api/account.dart' as zkool_account;
import 'package:zkool/src/rust/api/coin.dart' as zkool_coin;
import 'package:zkool/src/rust/api/sync.dart' as zkool_sync;
import 'package:zkool/src/rust/api/pay.dart' as zkool_pay;
import 'package:zkool/src/rust/api/network.dart' as zkool_network;
import 'package:zkool/src/rust/pay.dart' as zkool_paydart;
import 'package:zkool/src/rust/api/sweep.dart' as zkool_sweep;

class ZcashTaddressRotation {
  static bool _isStarted = false;
  static zkool_coin.Coin get c => ZcashWalletBase.c;
  static const int _unusedBuffer = 10;
  static const int _gapLimit = 5;

  static zkool_account.Seed seedForOffset(final zkool_account.Seed seed) {
    final seedStr = "${seed.mnemonic} ${seed.phrase}".trim();
    final seedWords = seedStr.split(" ");
    if ([12, 24].contains(seedWords.length)) {
      seedWords.add("");
    }
    final lastI = seedWords.length - 1;
    final crc = CRC32.compute(seedStr);
    seedWords[lastI] += ":tgen:$crc";
    final phrase = seedWords.removeLast();
    return zkool_account.Seed(mnemonic: seedWords.join(" "), phrase: phrase, aindex: 0);
  }

  static bool zkoolAccountSeedIsEqual(final zkool_account.Seed a, final zkool_account.Seed b) {
    return a.mnemonic == b.mnemonic && a.phrase == b.phrase;
  }

  static bool isSeedForWallet(
    final zkool_account.Seed? mainWallet,
    final zkool_account.Seed? subWallet,
  ) {
    if (mainWallet == null || subWallet == null) return false;
    return zkoolAccountSeedIsEqual(seedForOffset(mainWallet), subWallet);
  }

  static Map<int, Set<String>> rotationAddresses = {};
  static Map<int, Set<String>> rotationAddressesUsable = {};
  static Map<int, List<ZkoolTx>> shieldedAccountsTx = {};
  static bool _sweepJobRunning = false;
  static DateTime? _lastSweepBroadcastAt;
  static final Set<int> _backfilledRotationAccounts = {};

  static Future<void> _resyncRotationAccount(final int rotationAccount) async {
    await ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) => zkool_account.resetSync(id: rotationAccount, c: c),
    );
  }

  static Future<void> init() async {
    printV("Deserializing previous state");
    if (_isStarted) {
      return;
    }
    _isStarted = true;
    final pfw = await pathForWalletTypeDir(type: WalletType.zcash);
    final cacheFile = File(p.join(pfw, "zec-taddr.v2.json"));
    try {
      if (cacheFile.existsSync()) {
        await deserialize(cacheFile.readAsBytesSync());
      }
    } catch (e) {
      printV("Failed to deserialize T address DB for zcash: $e");
      try {
        final backup = File(
          p.join(pfw, "zec-taddr.v2.json.bak.${DateTime.now().millisecondsSinceEpoch}"),
        );
        await cacheFile.copy(backup.path);
        printV("Backed up corrupt T address DB to ${backup.path}");
      } catch (backupError) {
        printV("T address DB backup failed: $backupError");
      }
      rotationAddresses = {};
      rotationAddressesUsable = {};
      shieldedAccountsTx = {};
    }

    unawaited(
      (() async {
        await Future.delayed(const Duration(seconds: 2));
        return _jobRunner();
      })(),
    );
  }

  static Future<void> serializeToFile() async {
    final pfw = await pathForWalletTypeDir(type: WalletType.zcash);
    final f = File(p.join(pfw, "zec-taddr.v2.json"));
    f.writeAsBytesSync(serialize());
  }

  static Uint8List serialize() {
    final data = {
      "rotationAddresses": rotationAddresses.map(
        (final k, final v) => MapEntry(k.toRadixString(16), v.toList()),
      ),
      "rotationAddressesUsable": rotationAddressesUsable.map(
        (final k, final v) => MapEntry(k.toRadixString(16), v.toList()),
      ),
      "shieldedAccountsTx": shieldedAccountsTx.map(
        (final k, final v) => MapEntry(k.toRadixString(16), v.map((final v) => v.toJson()).toList()),
      ),
    };

    if (kDebugMode) {
      return utf8.encode(JsonEncoder.withIndent("    ").convert(data));
    }
    return utf8.encode(jsonEncode(data));
  }

  static Future<void> deserialize(final Uint8List bytes) async {
    final Map<dynamic, dynamic> data = jsonDecode(utf8.decode(bytes));

    final rawRotationAddresses = data["rotationAddresses"];
    if (rawRotationAddresses is Map<String, dynamic>) {
      rotationAddresses = rawRotationAddresses.map(
        (final k, final v) => MapEntry(
          int.parse(k, radix: 16),
          (v as List).map((final a) => a as String).toSet(),
        ),
      );
    }

    final rawRotationAddressesUsable = data["rotationAddressesUsable"];
    if (rawRotationAddressesUsable is Map<String, dynamic>) {
      rotationAddressesUsable = rawRotationAddressesUsable.map(
        (final k, final v) => MapEntry(
          int.parse(k, radix: 16),
          (v as List).map((final a) => a as String).toSet(),
        ),
      );
    }

    for (final entry in rotationAddresses.entries) {
      final usable = rotationAddressesUsable[entry.key];
      if (usable == null) {
        continue;
      }
      rotationAddressesUsable[entry.key] =
          usable.where(entry.value.contains).toSet();
    }

    try {
      final rawShieldedAccountsTx = data["shieldedAccountsTx"];
      if (rawShieldedAccountsTx is Map<String, dynamic>) {
        shieldedAccountsTx = rawShieldedAccountsTx.map(
          (final k, final v) => MapEntry(
            int.parse(k, radix: 16),
            (v as List)
                .map(
                  (final a) => ZkoolTx.fromJson(Map<String, dynamic>.from(a as Map)),
                )
                .toList(),
          ),
        );
      }
    } catch (e) {
      printV("shieldedAccountsTx deserialize failed, clearing tx cache: $e");
      shieldedAccountsTx = {};
    }
  }

  static Future<void> _markUsedRotationAddresses(
    final int mainAccountId,
    final int rotationAccountId,
  ) async {
    final usable = rotationAddressesUsable[mainAccountId];
    final known = rotationAddresses[mainAccountId];
    if (usable == null || usable.isEmpty || known == null || known.isEmpty) {
      return;
    }
    final withActivity = await ZcashWalletBase.runWithCoin(
      accountId: rotationAccountId,
      func: (final coin) => zkool_account.fetchTransparentAddressTxCount(c: coin),
    );
    for (final entry in withActivity) {
      if (entry.txCount > 0 && known.contains(entry.address)) {
        if (usable.remove(entry.address)) {
          printV(
            "marked used (on-chain): ${entry.address}, usable left: ${usable.length}",
          );
        }
      }
    }
  }

  static Future<int?> getRotationAccountForMainAccount(final int mainAccountId) async {
    try {
      await ZcashWalletBase.runWithCoinMutex.acquire();
      final wSeed = await zkool_account.getAccountSeed(c: c, account: mainAccountId);
      if (wSeed == null) {
        printV("Not running Taddr rotation - seed not found");
        return null;
      }
      final seed = seedForOffset(wSeed);
      final accs = await zkool_account.listAccounts(c: c);
      for (int i = 0; i < accs.length; i++) {
        final accSeed = await zkool_account.getAccountSeed(c: c, account: accs[i].id);
        if (accSeed?.mnemonic == seed.mnemonic &&
            accSeed?.phrase == seed.phrase &&
            accSeed?.aindex == seed.aindex) {
          return accs[i].id;
        }
      }

      zkool_account.Account? acc;
      for (final a in accs) {
        if (a.id == mainAccountId) {
          acc = a;
          break;
        }
      }
      if (acc == null) {
        printV("Main account $mainAccountId not found for Taddr rotation");
        return null;
      }

      final name = CRC32.compute(wSeed.mnemonic).toString();
      final id = await newAccount(
        name: name,
        seed: seed.mnemonic,
        passphrase: seed.phrase,
        height: acc.birth,
        aindex: seed.aindex,
      );
      return id;
    } finally {
      ZcashWalletBase.runWithCoinMutex.release();
    }
  }

  static Future<void> _runTransparentScanner({
    required final int mainAccountId,
    required final int rotationAccount,
    required final int chainHeight,
    required final int needed,
  }) async {
    var newAdded = 0;
    await ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) async {
        final sc = await zkool_sweep.TransparentScanner.newInstance();
        final sub = sc.run(endHeight: chainHeight, gapLimit: _gapLimit, c: c);
        final completer = Completer<void>();
        var completed = false;
        Timer? idleTimer;

        void completeScanner() {
          if (completed) {
            return;
          }
          completed = true;
          idleTimer?.cancel();
          if (!completer.isCompleted) {
            completer.complete();
          }
        }

        void bumpIdleTimer() {
          idleTimer?.cancel();
          idleTimer = Timer(const Duration(seconds: 3), () {
            unawaited(sc.cancel());
            completeScanner();
          });
        }

        sub.listen(
          (final a) {
            rotationAddresses[mainAccountId] ??= {};
            if (!rotationAddresses[mainAccountId]!.add(a)) {
              bumpIdleTimer();
              return;
            }
            rotationAddressesUsable[mainAccountId] ??= {};
            rotationAddressesUsable[mainAccountId]!.add(a);
            newAdded++;
            unawaited(serializeToFile());
            bumpIdleTimer();
            if (newAdded >= needed) {
              unawaited(sc.cancel());
            }
          },
          onDone: completeScanner,
          onError: (final e) {
            printV("transparent scanner: $e");
            completeScanner();
          },
          cancelOnError: true,
        );
        bumpIdleTimer();
        await completer.future.timeout(
          const Duration(seconds: 45),
          onTimeout: () {
            printV("transparent scanner timed out after 45s");
            unawaited(sc.cancel());
            completeScanner();
          },
        );
        // zkool's transparent_sweep continues in a background task after the
        // stream closes; give it time to register funded addresses in the DB.
        await Future.delayed(const Duration(seconds: 8));
      },
    );
    printV("transparent scanner added $newAdded address(es)");
    if (newAdded > 0) {
      await _resyncRotationAccount(rotationAccount);
    }
  }

  static bool _isWalletSynced(final int mainAccountId) {
    final wallet = ZcashWalletBase.walletsByAccountId[mainAccountId];
    return wallet != null && wallet.syncStatus is SyncedSyncStatus;
  }

  static Future<BigInt> _rotationAccountBalance(final int rotationAccount) async {
    return ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) async {
        final b = await zkool_sync.balance(c: c);
        var total = BigInt.zero;
        for (final v in b.field0) {
          total += v;
        }
        return total;
      },
    );
  }

  static Future<BigInt> _rotationTransparentBalance(final int rotationAccount) async {
    return ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) async {
        final b = await zkool_sync.balance(c: c);
        return b.field0.elementAt(0);
      },
    );
  }

  static Future<List<ZkoolTx>> _loadTxHistory(final int accountId) async {
    return ZcashWalletBase.runWithCoin(
      accountId: accountId,
      func: (final coin) async {
        final txsI = await zkool_account.listTxHistory(c: coin);
        final txs = <ZkoolTx>[];
        for (int i = 0; i < txsI.length; i++) {
          final tx = txsI[i];
          try {
            final details = await zkool_account.getTxDetails(idTx: tx.id, c: coin);
            txs.add(ZkoolTx(tx, details));
          } catch (e) {
            printV("getTxDetails skipped for tx ${tx.id}: $e");
          }
        }
        return txs;
      },
    );
  }

  static Future<void> createAndSweepTAddresses() async {
    if (_sweepJobRunning) {
      return;
    }
    _sweepJobRunning = true;
    try {
      final mainAccountIds = ZcashWalletBase.walletsByAccountId.keys.toList();
      if (mainAccountIds.isEmpty) {
        await createAndSweepTAddressesForAccount(c.account);
        return;
      }
      for (final mainAccountId in mainAccountIds) {
        try {
          await createAndSweepTAddressesForAccount(mainAccountId);
        } catch (e, s) {
          printV("createAndSweepTAddresses for $mainAccountId error: $e");
          s.toString().split("\n").forEach(printV);
        }
      }
    } finally {
      _sweepJobRunning = false;
    }
  }

  static Future<void> createAndSweepTAddressesForAccount(final int cId) async {
    if (!_isWalletSynced(cId)) {
      printV("rotation sweep waiting for wallet sync (account $cId)");
      return;
    }

    final lastSweep = _lastSweepBroadcastAt;
    if (lastSweep != null &&
        lastSweep.isAfter(DateTime.now().subtract(const Duration(seconds: 120)))) {
      return;
    }

    printV("createAndSweepTAddresses for account $cId");
    final chainHeight = await zkool_network.getCurrentHeight(c: c);
    // final syncHeight = ZcashWalletBase.dbHeight;
    // if (chainHeight != syncHeight) {
    //   printV(
    //     "Waiting for sync to finish: chainHeight(${chainHeight}) != syncHeight(${syncHeight})",
    //   );
    //   return;
    // }


    final rotationAccount = await getRotationAccountForMainAccount(cId);

    if (rotationAccount == null) {
      printV("rotation account is null, bailing out");
      return;
    }

    if (_backfilledRotationAccounts.add(rotationAccount)) {
      await _resyncRotationAccount(rotationAccount);
    }

    await _markUsedRotationAddresses(cId, rotationAccount);

    final usableCount = rotationAddressesUsable[cId]?.length ?? 0;
    final needed = _unusedBuffer - usableCount;
    if (needed > 0) {
      printV("Replenishing $needed Taddrs (usable: $usableCount, buffer: $_unusedBuffer)");
      await _runTransparentScanner(
        mainAccountId: cId,
        rotationAccount: rotationAccount,
        chainHeight: chainHeight,
        needed: needed,
      );
    } else {
      printV("Taddr buffer satisfied ($usableCount unused ready)");
    }

    await serializeToFile();
    await _refreshWalletAddresses(cId);

    BigInt bal = BigInt.zero;
    BigInt transparentBal = BigInt.zero;

    try {
      bal = await _rotationAccountBalance(rotationAccount);
      transparentBal = await _rotationTransparentBalance(rotationAccount);
      printV(
        "rotation account $rotationAccount balance: total=$bal transparent=$transparentBal",
      );
    } catch (e) {
      printV("getTBalance: $e");
      return;
    }
    if (bal < BigInt.from(30000)) {
      await updateCache(mainAccountId: cId);
      await _refreshWalletAfterRotationChange(cId);
      return;
    }

    final toAddress = await ZcashWalletBase.runWithCoin(
      accountId: cId,
      func: (final c) async {
        final addrs = await zkool_account.getAddresses(c: c, uaPools: 7);
        final orchard = addrs.oaddr;
        if (orchard == null || orchard.isEmpty) {
          throw Exception('Orchard address unavailable for rotation sweep');
        }
        return orchard;
      },
    );
    final result = await ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) async {
        final tx = await zkool_pay.prepare(
          recipients: [
            zkool_paydart.Recipient(
              assetBase: zecBase,
              address: toAddress,
              amount: bal,
            )
          ],
          options: zkool_pay.PaymentOptions(
            srcPools: 1,
            recipientPaysFee: true,
            smartTransparent: false,
          ),
          c: c,
        );
        printV("getLatestHeight");
        final height = await zkool_network.getCurrentHeight(c: c);
        printV("signTransaction");
        final signTx = await zkool_pay.signTransaction(pczt: tx, c: c);
        printV("extractTransaction");
        final txBytes = await zkool_pay.extractTransaction(package: signTx);
        printV("broadcastTransaction");
        return zkool_pay.broadcastTransaction(height: height, txBytes: txBytes, c: c);
      },
    );
    printV("rotation sweep broadcast: $result");
    if (result.isEmpty) {
      printV("Unknown error");
      throw Exception("Unknown error");
    }

    await ZcashWalletService.addShieldedTx(result);
    _lastSweepBroadcastAt = DateTime.now();
    await updateCache(mainAccountId: cId);
    await _refreshWalletAfterRotationChange(cId);
  }

  static Future<void> _refreshWalletAfterRotationChange(final int mainAccountId) async {
    final wallet = ZcashWalletBase.walletsByAccountId[mainAccountId];
    if (wallet == null) {
      return;
    }
    unawaited(wallet.updateTransactions());
    unawaited(wallet.updateBalance());
  }

  static Future<void> updateCache({required final int mainAccountId}) async {
    final rotationAccount = await getRotationAccountForMainAccount(mainAccountId);
    if (rotationAccount == null) {
      printV("rotationAccount is null");
      return;
    }
    await _markUsedRotationAddresses(mainAccountId, rotationAccount);
    final txs = _relevantRotationTxs(mainAccountId, await _loadTxHistory(rotationAccount));
    shieldedAccountsTx[mainAccountId] = txs;
    if (mainAccountId != rotationAccount &&
        shieldedAccountsTx.containsKey(rotationAccount)) {
      shieldedAccountsTx.remove(rotationAccount);
    }

    final txHist = shieldedAccountsTx[mainAccountId]!;
    for (int i = 0; i < txHist.length; i++) {
      final tx = txHist[i];
      if (tx.direction == TransactionDirection.outgoing) {
        await ZcashWalletService.addShieldedTx(tx.txHash);
      }
    }
    await serializeToFile();
    await _refreshWalletAddresses(mainAccountId);
    await _refreshWalletAfterRotationChange(mainAccountId);
    return;
  }

  static Future<void> _refreshWalletAddresses(final int mainAccountId) async {
    final wallet = ZcashWalletBase.walletsByAccountId[mainAccountId];
    if (wallet == null) {
      return;
    }
    try {
      await wallet.walletAddresses.init();
    } catch (e) {
      printV("rotation address refresh: $e");
    }
  }

  static List<ZkoolTx> _relevantRotationTxs(
    final int mainAccountId,
    final List<ZkoolTx> txs,
  ) {
    // Rotation sub-account only exists for disposable T-address receives.
    // Never hide incoming txs based on the local address cache — that cache can
    // be empty or stale after a failed deserialize.
    return txs;
  }

  static List<ZkoolTx> rotationTxsForMainAccount(final int mainAccountId) {
    final direct = shieldedAccountsTx[mainAccountId];
    if (direct == null || direct.isEmpty) {
      return const [];
    }
    return _relevantRotationTxs(mainAccountId, direct);
  }

  static Future<zkool_account.Account?> accountForSeed(final zkool_account.Seed seed) async {
    final accounts = await zkool_account.listAccounts(c: c);
    if (accounts.isEmpty) return null;
    for (int i = 0; i < accounts.length; i++) {
      final acc = accounts[i];
      final backup = await zkool_account.getAccountSeed(c: c, account: acc.id);
      if (backup?.mnemonic == seed.mnemonic && backup?.phrase == seed.phrase) {
        return acc;
      }
    }
    return null;
  }

  static Future<void> _jobRunner() async {
    for (;;) {
      try {
        await Future.delayed(Duration(seconds: 5));
        await createAndSweepTAddresses();
      } catch (e, s) {
        printV("createAndSweepTAddresses error: $e");
        s.toString().split("\n").forEach(printV);
      } finally {
        await Future.delayed(Duration(seconds: 30));
      }
    }
  }

  static Future<String?> addressForAccount(
    final int accountId,
  ) async {
    return rotationAddressesUsable[accountId]?.firstOrNull;
  }

  static Future<Iterable<String>?> allAddressesForAccount(final int accountId) async {
    return rotationAddresses[accountId];
  }

  static Future<List<String>?> allUsedAddressesForAccount(final int accountId) async {
    final allAccCopy = rotationAddresses[accountId]?.map((final a) => a).toList();
    allAccCopy?.removeWhere((final a) => rotationAddressesUsable[accountId]?.contains(a) == true);
    return allAccCopy;
  }

  static Future<int> newAccount({
    required final String name,
    required final String seed,
    required final String passphrase,
    required final int height,
    required final int aindex,
  }) async {
    final id = await zkool_account.newAccount(
      na: zkool_account.NewAccount(
        name: name,
        restore: true,
        passphrase: passphrase,
        key: seed,
        aindex: aindex,
        birth: height,
        folder: '',
        useInternal: true,
        internal: false,
        ledger: false,
      ),
      c: c,
    );
    return id;
  }
}
