// create offset wallets for T address rotation.
// Each address is considered one time use, if it receives less than 15000 zatoshi balance will be essentially burned.
//
// This class takes address index as constructor, and will create 10 addresses by default, if any of the addresses gets used
// it will be moved out of the pool
//
// T addresses are generated by creating new wallets with an extra seed word (or appending to "passphrase") the following
// :tgen:${CRC32(seed)}
// It is highly unlikely for users to create a wallet with that specific last word and add index to it
// We could leverage other fields such as native account index alone, but users may want to set that in future
// This solution is rather simple and if standard would get estabilished for this purpose it can be easily
// turned off and replaced with proper solution.

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:cw_core/pathForWallet.dart';
import 'package:cw_core/utils/print_verbose.dart';
import 'package:cw_core/wallet_type.dart';
import 'package:cw_zcash/src/util/crc32.dart';
import 'package:cw_zcash/src/zcash_wallet.dart';
import 'package:cw_zcash/src/zcash_wallet_service.dart';
import 'package:cw_zcash/src/zkooltx.dart';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;
import 'package:zkool/src/rust/api/account.dart' as zkool_account;
import 'package:zkool/src/rust/api/coin.dart' as zkool_coin;
import 'package:zkool/src/rust/api/sync.dart' as zkool_sync;
import 'package:zkool/src/rust/api/pay.dart' as zkool_pay;
import 'package:zkool/src/rust/api/network.dart' as zkool_network;
import 'package:zkool/src/rust/pay.dart' as zkool_paydart;
import 'package:zkool/src/rust/api/sweep.dart' as zkool_sweep;
import 'package:mutex/mutex.dart';

class ZcashTaddressRotation {
  static bool _isStarted = false;
  static zkool_coin.Coin get c => ZcashWalletBase.c;

  static zkool_account.Seed seedForOffset(final zkool_account.Seed seed) {
    final seedStr = "${seed.mnemonic} ${seed.phrase}".trim();
    final seedWords = seedStr.split(" ");
    if ([12, 24].contains(seedWords.length)) {
      seedWords.add("");
    }
    final lastI = seedWords.length - 1;
    final crc = CRC32.compute(seedStr);
    seedWords[lastI] += "${seed.phrase}:tgen:${crc}";
    final phrase = seedWords.removeLast();
    return zkool_account.Seed(mnemonic: seedWords.join(" "), phrase: phrase, aindex: 1);
  }

  static bool zkoolAccountSeedIsEqual(final zkool_account.Seed a, final zkool_account.Seed b) {
    return a.mnemonic == b.mnemonic && a.phrase == b.phrase;
  }

  static bool isSeedForWallet(
    final zkool_account.Seed? mainWallet,
    final zkool_account.Seed? subWallet,
  ) {
    if (mainWallet == null || subWallet == null) return false;
    return zkoolAccountSeedIsEqual(seedForOffset(mainWallet), subWallet);
  }

  static Map<int, Set<String>> rotationAddresses = {};
  static Map<int, Set<String>> rotationAddressesUsable = {};
  static Map<int, List<ZkoolTx>> shieldedAccountsTx = {};

  static Future<void> init() async {
    printV("Deserializing previous state");
    if (_isStarted) {
      return;
    }
    _isStarted = true;
    final pfw = await pathForWalletTypeDir(type: WalletType.zcash);
    try {
      final f = File(p.join(pfw, "zec-taddr.v2.json"));
      await deserialize(f.readAsBytesSync());
    } catch (e) {
      printV("Failed to deserialize T address DB for zcash, it doesn't really matter: $e");
    }

    unawaited(
      (() async {
        await Future.delayed(Duration(seconds: 15));
        return _jobRunner();
      })(),
    );
  }

  static Future<void> serializeToFile() async {
    final pfw = await pathForWalletTypeDir(type: WalletType.zcash);
    final f = File(p.join(pfw, "zec-taddr.v2.json"));
    f.writeAsBytesSync(serialize());
  }

  static Uint8List serialize() {
    final data = {
      "rotationAddresses": rotationAddresses.map(
        (final k, final v) => MapEntry(k.toRadixString(16), v.toList()),
      ),
      "rotationAddressesUsable": rotationAddressesUsable.map(
        (final k, final v) => MapEntry(k.toRadixString(16), v.toList()),
      ),
      "shieldedAccountsTx": shieldedAccountsTx.map(
        (final k, final v) => MapEntry(k.toRadixString(16), v.map((final v) => v.toJson()).toList()),
      ),
    };

    if (kDebugMode) {
      return utf8.encode(JsonEncoder.withIndent("    ").convert(data));
    }
    return utf8.encode(jsonEncode(data));
  }

  static Future<void> deserialize(final Uint8List bytes) async {
    // todo: replace keys with sums and reverse in serialize
    // final List<String> seeds = [];
    // for (int i = 0; i < accounts.length; i++) {
    //   final acc = accounts[i];
    //   final backup = WarpApi.getBackup(coin, acc.id);
    //   await WarpApi.transparentSync(coin, acc.id, syncHeight);
    //   seeds.add(backup.seed!);
    // }
    try {
      final accs = await zkool_account.listAccounts(c: c);
      final Map<dynamic, dynamic> data = jsonDecode(utf8.decode(bytes));
      rotationAddresses = (data["rotationAddresses"] as Map<String, dynamic>).map(
        (final k, final v) => MapEntry(
          int.parse(k, radix: 16),
          (v as List).map((final a) => a as String).toSet(),
        ),
      );
      rotationAddressesUsable = (data["rotationAddressesUsable"] as Map<String, dynamic>).map(
        (final k, final v) => MapEntry(
          int.parse(k, radix: 16),
          (v as List).map((final a) => a as String).toSet(),
        ),
      );
      shieldedAccountsTx = (data["shieldedAccountsTx"] as Map<String, dynamic>).map(
        (final k, final v) => MapEntry(
          int.parse(k, radix: 16),
          (v as List)
              .map(
                (final a) => ZkoolTx.fromJson(a),
              )
              .toList(),
        ),
      );
    } catch (e) {
      rethrow;
    }
  }

  static Uint8List atob(final String value) =>
      Uint8List.fromList(List<int>.from(base64.decode(value)));

  static Future<int?> getRotationAccountForCurrentAccount() async {
    final currentHeight = await zkool_network.getCurrentHeight(c: c);
    try {
      await ZcashWalletBase.runWithCoinMutex.acquire();
      final wSeed = await zkool_account.getAccountSeed(c: c, account: c.account);
      if (wSeed == null) {
        printV("Not running Taddr rotation - seed not found");
        return null;
      }
      final seed = seedForOffset(wSeed);
      final accs = await zkool_account.listAccounts(c: c);
      for (int i = 0; i < accs.length; i++) {
        final accSeed = await zkool_account.getAccountSeed(c: c, account: accs[i].id);
        if (accSeed?.mnemonic == seed.mnemonic &&
            accSeed?.phrase == seed.phrase &&
            accSeed?.aindex == seed.aindex) {
          return accs[i].id;
        }
      }

      final acc = accs.firstWhere((final a) => a.id == c.account);

      final name = CRC32.compute(wSeed.mnemonic).toString();
      final id = await newAccount(
        name: name,
        seed: seed.mnemonic,
        passphrase: seed.phrase,
        height: acc.birth,
        aindex: seed.aindex,
      );
      return id;
    } finally {
      ZcashWalletBase.runWithCoinMutex.release();
    }
  }

  static Future<void> createAndSweepTAddresses() async {
    printV("createAndSweepTAddresses");
    final chainHeight = await zkool_network.getCurrentHeight(c: c);
    final syncHeight = ZcashWalletBase.dbHeight;
    // if (chainHeight != syncHeight) {
    //   printV(
    //     "Waiting for sync to finish: chainHeight(${chainHeight}) != syncHeight(${syncHeight})",
    //   );
    //   return;
    // }


    final rotationAccount = await getRotationAccountForCurrentAccount();

    if (rotationAccount == null) {
      printV("rotation account is null, bailing out");
      return;
    }

    final amt = 25 + (rotationAddresses[c.account]?.length??0) - (rotationAddressesUsable[c.account]?.length??0);
    await ZcashWalletBase.runWithCoinMutex.acquire();
    final cId = c.account;
    ZcashWalletBase.runWithCoinMutex.release();
    await ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) async {
        final sc = await zkool_sweep.TransparentScanner.newInstance();
        final sub = sc.run(endHeight: chainHeight, gapLimit: amt, c: c);
        final wait = Mutex();
        sub.listen(
          (final a) {
            rotationAddresses[cId] ??= {};
            rotationAddresses[cId]!.add(a);
          },
          onDone: () {
            if (wait.isLocked) wait.release();
          },
          onError: (final e) {
            if (wait.isLocked) wait.release();
            printV(e.toString());
          },
          cancelOnError: true,
        );
        await wait.acquire();
      },
    );

    final txList = await ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) => zkool_account.listTxHistory(c: c),
    );

    printV("txList: $txList");

    rotationAddressesUsable[cId] ??= {};
    rotationAddressesUsable[cId]!.addAll(rotationAddresses[cId] ?? {});
    for (int i = 0; i < txList.length; i++) {
      final tx = txList[i];
      final details = await ZcashWalletBase.runWithCoin(
        accountId: rotationAccount,
        func: (final c) => zkool_account.getTxDetails(c: c, idTx: tx.id),
      );
      for (int j = 0; j < details.outputs.length; j++) {
        final out = details.outputs[j];
        rotationAddressesUsable[cId]?.removeWhere((final a) => a == out.address);
      }
    }

    BigInt bal = BigInt.from(0);

    try {
      final b = await ZcashWalletBase.runWithCoin(
        accountId: rotationAccount,
        func: (final c) => zkool_sync.balance(c: c),
      );
      bal += b.field0.reduce((final a, final b) => a + b);
    } catch (e) {
      printV("getTBalance: $e");
      return;
    }
    if (bal < BigInt.from(30000)) {
      await updateCache(mainAccountId: cId);
      return;
    };

    final toAddress = await ZcashWalletBase.runWithCoin(
      accountId: cId,
      func: (final c) async {
        final addrs = await zkool_account.getAddresses(c: c, uaPools: 7);
        final orchard = addrs.oaddr;
        if (orchard == null || orchard.isEmpty) {
          throw Exception('Orchard address unavailable for rotation sweep');
        }
        return orchard;
      },
    );
    final result = await ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) async {
        final tx = await zkool_pay.prepare(
          recipients: [zkool_paydart.Recipient(address: toAddress, amount: bal)],
          options: zkool_pay.PaymentOptions(
            srcPools: 1,
            recipientPaysFee: true,
            smartTransparent: false,
          ),
          c: c,
        );
        printV("getLatestHeight");
        final height = await zkool_network.getCurrentHeight(c: c);
        printV("signTransaction");
        final signTx = await zkool_pay.signTransaction(pczt: tx, c: c);
        printV("extractTransaction");
        final txBytes = await zkool_pay.extractTransaction(package: signTx);
        printV("broadcastTransaction");
        return zkool_pay.broadcastTransaction(height: height, txBytes: txBytes, c: c);
      },
    );
    printV("result");
    if (result.isEmpty) {
      printV("Unknown error");
      throw Exception("Unknown error");
    }

    await updateCache(mainAccountId: cId);

    await Future.delayed(Duration(seconds: 120)); // let it be
    return createAndSweepTAddresses();
  }

  static Future<void> updateCache({required final int mainAccountId}) async {
    final rotationAccount = await getRotationAccountForCurrentAccount();
    if (rotationAccount == null) {
      printV("rotationAccount is null");
      return;
    }
    final txsI = await ZcashWalletBase.runWithCoin(
      accountId: rotationAccount,
      func: (final c) => zkool_account.listTxHistory(c: c),
    );
    final txsA = await Future.wait(
      txsI.map((final tx) async => ZcashWalletBase.runWithCoin(
        accountId: rotationAccount,
        func: (final c) => zkool_account.getTxDetails(idTx: tx.id, c: c),
      ),
    ));
    final txs = <ZkoolTx>[];
    for (int i = 0; i < txsI.length; i++) {
      txs.add(ZkoolTx(txsI[i], txsA[i]));
    }
    shieldedAccountsTx[mainAccountId] ??= [];
    final txsCrc = txs.map((final t) => t.txHash);
    shieldedAccountsTx[mainAccountId]!.removeWhere((final t) => txsCrc.contains(t.txHash));
    shieldedAccountsTx[mainAccountId]!.addAll(txs);
    if (mainAccountId != rotationAccount &&
        shieldedAccountsTx.containsKey(rotationAccount)) {
      shieldedAccountsTx.remove(rotationAccount);
    }

    final txHist = shieldedAccountsTx[mainAccountId]!;
    for (int i = 0; i < txHist.length; i++) {
      final tx = txHist[i];
      if (tx.value < BigInt.from(0)) {
        await ZcashWalletService.addShieldedTx(tx.txHash);
      }
    }
    await serializeToFile();
    return;
  }

  static List<ZkoolTx> rotationTxsForMainAccount(final int mainAccountId) {
    final direct = shieldedAccountsTx[mainAccountId];
    if (direct != null && direct.isNotEmpty) {
      return direct;
    }
    for (final entry in shieldedAccountsTx.entries) {
      if (entry.key != mainAccountId && entry.value.isNotEmpty) {
        shieldedAccountsTx[mainAccountId] = entry.value;
        shieldedAccountsTx.remove(entry.key);
        return entry.value;
      }
    }
    return const [];
  }

  static Future<zkool_account.Account?> accountForSeed(final zkool_account.Seed seed) async {
    final accounts = await zkool_account.listAccounts(c: c);
    if (accounts.isEmpty) return null;
    for (int i = 0; i < accounts.length; i++) {
      final acc = accounts[i];
      final backup = await zkool_account.getAccountSeed(c: c, account: acc.id);
      if (backup?.mnemonic == seed.mnemonic && backup?.phrase == seed.phrase) {
        return acc;
      }
    }
    return null;
  }

  static Future<void> _jobRunner() async {
    for (;;) {
      try {
        await Future.delayed(Duration(seconds: 5));
        await createAndSweepTAddresses();
      } catch (e, s) {
        printV(e);
        s.toString().split("\n").forEach(printV);
        rethrow;
      } finally {
        await Future.delayed(Duration(seconds: 30));
      }
    }
  }

  static Future<String?> addressForAccount(
    final int accountId,
  ) async {
    return rotationAddressesUsable[accountId]?.firstOrNull;
  }

  static Future<Iterable<String>?> allAddressesForAccount(final int accountId) async {
    return rotationAddresses[accountId];
  }

  static Future<List<String>?> allUsedAddressesForAccount(final int accountId) async {
    final allAccCopy = rotationAddresses[accountId]?.map((final a) => a).toList();
    allAccCopy?.removeWhere((final a) => rotationAddressesUsable[accountId]?.contains(a) == true);
    return allAccCopy;
  }

  static Future<int> newAccount({
    required final String name,
    required final String seed,
    required final String passphrase,
    required final int height,
    required final int aindex,
  }) async {
    final id = await zkool_account.newAccount(
      na: zkool_account.NewAccount(
        name: name,
        restore: true,
        passphrase: passphrase,
        key: seed,
        aindex: aindex,
        birth: height,
        folder: '',
        useInternal: false,
        internal: false,
        ledger: false,
      ),
      c: c,
    );
    return id;
  }
}
