name: cw_zcash
description: Zcash library for cake wallet
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cw_core:
    path: ../cw_core
  mobx: ^2.6.0
  bip39: ^1.0.6
  mutex: ^3.1.0

  path: any
  flat_buffers: any
  zkool:
    # path: ../../zkool2
    git:
      url: https://github.com/cake-tech/zkool2.git
      ref: 36e72b530c274c4a54a6127aadb94886e84d67bf

  path_provider: any
  sqflite_common_ffi: any
dependency_overrides:
  decimal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.15.0
  mobx_codegen: ^2.7.7
#  hive_generator: ^2.0.1
  ffigen: ^20.1.1
