

analyzer:
  exclude: [
    build/**,
    scripts/**,
    lib/**.g.dart,
    cw_core/lib/**.g.dart,
    cw_haven/lib/**.g.dart,
    cw_monero/lib/**.g.dart,
    cw_mweb/lib/**.g.dart,
    lib/generated/*.dart,
    cw_monero/ios/External/**,
    cw_shared_external/**,
    shared_external/**,
    ]
  language:
    strict-casts: true
    strict-raw-types: true

plugins:
  cw_custom_lints:
    path: cw_custom_lints

linter:
  rules:
    - cancel_subscriptions
    - always_declare_return_types
    - prefer_final_fields
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - annotate_overrides
    - annotate_redeclares
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cast_nullable_to_non_nullable
    - collection_methods_unrelated_type
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - flutter_style_todos
    - hash_and_equals
    - implicit_reopen
    - library_private_types_in_public_api
    - non_constant_identifier_names
    - only_throw_errors
    - package_names
    - prefer_asserts_with_message
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_double_quotes
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_wheretype
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - require_trailing_commas
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - unawaited_futures
    - unnecessary_async
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - unnecessary_underscores
    - unreachable_from_main
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - use_colored_box
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_null_aware_elements
    - use_raw_strings
    - use_rethrow_when_possible
    - use_string_buffers
    - use_super_parameters
    - use_truncating_division
    - valid_regexps
    - void_checks
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - null_closures
    - no_wildcard_variable_uses




formatter:
  page_width: 100
