#!/bin/bash

set -euo pipefail

# Runner knobs, all overridable from the environment:
#   SUITE_DIR             directory to collect *_test.dart suites from (default integration_test/suites)
#   TEST_TIER             tier0, tier1 or all, narrows SUITE_DIR to a tier subdirectory
#   PLATFORM              android, linux or auto, picks the between-suite data reset
#   ANDROID_APP_ID        package cleared between suites on android (default read from android/app.properties)
#   PREBUILT_APK          prebuilt apk passed to flutter drive, skips rebuilding per suite.
#                         Dart defines must already be baked into this apk at build time.
#   EXTRA_DART_DEFINES    comma separated KEY=VALUE pairs forwarded as --dart-define flags
#   FLUTTER_DEVICE        device id passed to flutter drive, needed when several devices are attached
#   TEST_TIMEOUT          per-attempt timeout in seconds, applied when the timeout command exists (default 1800)
#   RETRY_COUNT           retries per suite after a failure (default 1)
#   REMOVE_DATA_DIRECTORY set to N to keep app data between suites (default wipes it)

SUITE_DIR=${SUITE_DIR:-integration_test/suites}
TEST_TIER=${TEST_TIER:-all}
PLATFORM=${PLATFORM:-auto}
TEST_TIMEOUT=${TEST_TIMEOUT:-1800}
RETRY_COUNT=${RETRY_COUNT:-1}
REMOVE_DATA_DIRECTORY=${REMOVE_DATA_DIRECTORY:-Y}
EXTRA_DART_DEFINES=${EXTRA_DART_DEFINES:-}
PREBUILT_APK=${PREBUILT_APK:-}

# Linux desktop data directories to wipe between suites
DATA_DIRS=(
    "$HOME/.local/share/com.example.cake_wallet"
    "$HOME/Documents/cake_wallet"
    "$HOME/.config/cake_wallet"
)

# Each entry is "name|duration_seconds" so retries can never misalign names and durations
declare -a targets
declare -a passed_tests
declare -a failed_tests

cleanup() {
    echo "Received interrupt signal, cleaning up..."
    exit 1
}

trap cleanup SIGINT SIGTERM

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >&2
}

# Format seconds into hours, minutes, seconds
format_duration() {
    local seconds=$1
    local hours=$((seconds / 3600))
    local minutes=$(((seconds % 3600) / 60))
    local secs=$((seconds % 60))

    if (( hours > 0 )); then
        echo "${hours}h ${minutes}m ${secs}s"
    elif (( minutes > 0 )); then
        echo "${minutes}m ${secs}s"
    else
        echo "${secs}s"
    fi
}

resolve_platform() {
    if [[ "$PLATFORM" != "auto" ]]; then
        return
    fi

    # An attached android device or emulator means we drive android, anything else is desktop
    if command -v adb > /dev/null 2>&1 && adb devices 2>/dev/null | grep -q "device$"; then
        PLATFORM="android"
    else
        PLATFORM="linux"
    fi

    log "Resolved platform: $PLATFORM"
}

resolve_android_app_id() {
    if [[ -n "${ANDROID_APP_ID:-}" ]]; then
        return
    fi

    # app.properties is generated by scripts/android/app_properties.sh and holds the applicationId
    if [[ -f "android/app.properties" ]]; then
        ANDROID_APP_ID=$(grep '^id=' android/app.properties | cut -d'=' -f2)
    fi

    ANDROID_APP_ID=${ANDROID_APP_ID:-com.cakewallet.cake_wallet}
}

clean_data_directories() {
    if [[ "$REMOVE_DATA_DIRECTORY" != "Y" ]]; then
        return
    fi

    log "Cleaning app data..."

    if [[ "$PLATFORM" == "android" ]]; then
        # pm clear resets the app to a fresh install so every suite starts from onboarding
        adb shell pm clear "$ANDROID_APP_ID" > /dev/null 2>&1 || log "pm clear skipped, $ANDROID_APP_ID not installed yet"
        return
    fi

    for dir in "${DATA_DIRS[@]}"; do
        if [[ -d "$dir" ]]; then
            rm -rf "$dir" || error "Failed to remove $dir"
        fi
    done
}

build_drive_command() {
    drive_command=(flutter drive --driver=test_driver/integration_test.dart --dart-define=CI_BUILD=true)

    if [[ -n "${FLUTTER_DEVICE:-}" ]]; then
        drive_command+=("-d" "$FLUTTER_DEVICE")
    fi

    if [[ -n "$PREBUILT_APK" ]]; then
        drive_command+=("--use-application-binary=$PREBUILT_APK")
    fi

    if [[ -n "$EXTRA_DART_DEFINES" ]]; then
        IFS=',' read -ra defines <<< "$EXTRA_DART_DEFINES"
        for define in "${defines[@]}"; do
            drive_command+=("--dart-define=$define")
        done
    fi

    # timeout is not available on stock macOS, only apply it where it exists
    if command -v timeout > /dev/null 2>&1; then
        drive_command=(timeout "$TEST_TIMEOUT" "${drive_command[@]}")
    fi
}

# Run a single test with retry logic
run_test() {
    local test_file="$1"
    local test_name=$(basename "$test_file" .dart)
    local retry_count=0

    while (( retry_count <= RETRY_COUNT )); do
        log "Running test: $test_name (attempt $((retry_count + 1)))"

        # Clean data directories before each attempt so retries stay hermetic
        clean_data_directories

        local start_time=$(date +%s)

        if "${drive_command[@]}" --target="$test_file"; then
            local duration=$(( $(date +%s) - start_time ))

            log "PASS: $test_name ($(format_duration $duration))"
            passed_tests+=("$test_name|$duration")
            return 0
        else
            local duration=$(( $(date +%s) - start_time ))

            log "FAIL: $test_name ($(format_duration $duration))"

            if (( retry_count < RETRY_COUNT )); then
                log "Retrying test: $test_name"
                retry_count=$((retry_count + 1))
                sleep 5
            else
                failed_tests+=("$test_name|$duration")
                return 1
            fi
        fi
    done
}

write_github_summary() {
    if [[ -z "${GITHUB_STEP_SUMMARY:-}" ]]; then
        return
    fi

    {
        echo "### Integration tests ($SUITE_DIR, tier: $TEST_TIER)"
        echo ""
        echo "| Suite | Result | Duration |"
        echo "|---|---|---|"
        for entry in "${passed_tests[@]+"${passed_tests[@]}"}"; do
            echo "| ${entry%%|*} | pass | $(format_duration "${entry##*|}") |"
        done
        for entry in "${failed_tests[@]+"${failed_tests[@]}"}"; do
            echo "| ${entry%%|*} | fail | $(format_duration "${entry##*|}") |"
        done
    } >> "$GITHUB_STEP_SUMMARY"
}

main() {
    log "Starting integration test runner"

    local search_dir="$SUITE_DIR"
    if [[ "$TEST_TIER" != "all" ]]; then
        search_dir="$SUITE_DIR/$TEST_TIER"
    fi

    if [[ ! -d "$search_dir" ]]; then
        error "Suite directory not found: $search_dir"
        exit 1
    fi

    resolve_platform
    resolve_android_app_id
    build_drive_command

    log "Configuration: SUITE_DIR=$search_dir PLATFORM=$PLATFORM RETRY_COUNT=$RETRY_COUNT"

    # Only *_test.dart files are runnable suites, helpers and templates are never picked up
    while IFS= read -r -d $'\0' file; do
        targets+=("$file")
    done < <(find "$search_dir" -name "*_test.dart" -type f -print0 | sort -z)

    if (( ${#targets[@]} == 0 )); then
        error "No test files found in $search_dir"
        exit 1
    fi

    log "Found ${#targets[@]} test files"

    local overall_start_time=$(date +%s)

    # A failing suite must not stop the remaining suites, failures are collected for the summary
    for target in "${targets[@]}"; do
        run_test "$target" || true
    done

    local total_duration=$(( $(date +%s) - overall_start_time ))

    echo -e "\n===== Test Summary ====="
    echo "Total tests: ${#targets[@]}"
    echo "Passed: ${#passed_tests[@]}"
    echo "Failed: ${#failed_tests[@]}"
    echo "Total duration: $(format_duration $total_duration)"

    if (( ${#passed_tests[@]} > 0 )); then
        echo -e "\nPassed Tests:"
        for entry in "${passed_tests[@]}"; do
            echo "  - ${entry%%|*} ($(format_duration "${entry##*|}"))"
        done
    fi

    write_github_summary

    if (( ${#failed_tests[@]} > 0 )); then
        echo -e "\nFailed Tests:"
        for entry in "${failed_tests[@]}"; do
            echo "  - ${entry%%|*} ($(format_duration "${entry##*|}"))"
        done
        exit 1
    fi

    echo -e "\nAll tests passed successfully!"
}

main "$@"
