#!/bin/bash

set -euo pipefail

# Runner knobs, all overridable from the environment:
#   SUITE_DIR             directory to collect *_test.dart suites from, or a single suite file
#                         (default integration_test/suites)
#   TEST_TIER             tier0, tier1 or all, narrows SUITE_DIR to a tier subdirectory
#   PLATFORM              android, linux or auto, picks the between-suite data reset
#   ANDROID_APP_ID        package cleared between suites on android (default read from android/app.properties)
#   PREBUILT_APK          prebuilt apk passed to flutter drive, its dart defines are already baked in
#   EXTRA_DART_DEFINES    semicolon separated KEY=VALUE pairs, semicolons because values like
#                         CHAINS=solana,ethereum contain commas
#   FLUTTER_DEVICE        device id passed to flutter drive, needed when several devices are attached
#   TEST_TIMEOUT          per-attempt timeout in seconds (default 900)
#   RETRY_COUNT           retries per suite after a failure (default 1)
#   MAX_VOID_ATTEMPTS     extra attempts when the driver never attached (default 2)
#   MAX_TOTAL_VOID_ATTEMPTS  give up on the whole run after this many, the environment is broken (default 4)
#   REMOVE_DATA_DIRECTORY set to N to keep app data between suites (default wipes it)
#   SUMMARY_FILE          path to write a key=value summary of the run to, for reporting

SUITE_DIR=${SUITE_DIR:-integration_test/suites}
TEST_TIER=${TEST_TIER:-all}
PLATFORM=${PLATFORM:-auto}
TEST_TIMEOUT=${TEST_TIMEOUT:-900}
RETRY_COUNT=${RETRY_COUNT:-1}
MAX_VOID_ATTEMPTS=${MAX_VOID_ATTEMPTS:-2}
MAX_TOTAL_VOID_ATTEMPTS=${MAX_TOTAL_VOID_ATTEMPTS:-4}
REMOVE_DATA_DIRECTORY=${REMOVE_DATA_DIRECTORY:-Y}
EXTRA_DART_DEFINES=${EXTRA_DART_DEFINES:-}
SUMMARY_FILE=${SUMMARY_FILE:-}
PREBUILT_APK=${PREBUILT_APK:-}

# Linux desktop data directories to wipe between suites
DATA_DIRS=(
    "$HOME/.local/share/com.example.cake_wallet"
    "$HOME/Documents/cake_wallet"
    "$HOME/.config/cake_wallet"
)

# Entries are "name|duration_seconds", one string so a retry cannot misalign the two.
# Assigned empty rather than only declared, set -u treats a declared but never assigned array
# as unbound and that only shows up on a run where nothing fails.
targets=()
passed_tests=()
failed_tests=()
total_void_attempts=0

cleanup() {
    echo "Received interrupt signal, cleaning up..."
    exit 1
}

trap cleanup SIGINT SIGTERM

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >&2
}

format_duration() {
    local seconds=$1
    local hours=$((seconds / 3600))
    local minutes=$(((seconds % 3600) / 60))
    local secs=$((seconds % 60))

    if (( hours > 0 )); then
        echo "${hours}h ${minutes}m ${secs}s"
    elif (( minutes > 0 )); then
        echo "${minutes}m ${secs}s"
    else
        echo "${secs}s"
    fi
}

resolve_platform() {
    if [[ "$PLATFORM" != "auto" ]]; then
        return
    fi

    # An attached android device or emulator means we drive android, anything else is desktop
    if command -v adb > /dev/null 2>&1 && adb devices 2>/dev/null | grep -q "device$"; then
        PLATFORM="android"
    else
        PLATFORM="linux"
    fi

    log "Resolved platform: $PLATFORM"
}

resolve_android_app_id() {
    if [[ -n "${ANDROID_APP_ID:-}" ]]; then
        return
    fi

    # app.properties is generated by scripts/android/app_properties.sh and holds the applicationId
    if [[ -f "android/app.properties" ]]; then
        ANDROID_APP_ID=$(grep '^id=' android/app.properties | cut -d'=' -f2)
    fi

    ANDROID_APP_ID=${ANDROID_APP_ID:-com.cakewallet.cake_wallet}
}

# A wedged adb server is the usual reason the driver cannot attach to the app.
# Every call is bounded, adb wait-for-device blocks forever when the emulator is gone.
restart_adb() {
    if [[ "$PLATFORM" != "android" ]]; then
        return
    fi

    bounded 30 adb kill-server
    bounded 30 adb start-server
    bounded 60 adb wait-for-device

    if ! bounded 30 adb devices | grep -q "device$"; then
        error "No device is attached after restarting adb"
        return 1
    fi
}

bounded() {
    local limit="$1"
    shift

    if command -v timeout > /dev/null 2>&1; then
        timeout "$limit" "$@" 2>/dev/null || return 1
    elif command -v perl > /dev/null 2>&1; then
        perl -e 'alarm shift; exec @ARGV' "$limit" "$@" 2>/dev/null || return 1
    else
        "$@" 2>/dev/null || return 1
    fi
}

# The app never started, its logcat is the only place the reason shows up
capture_failure_logcat() {
    local test_name="$1"

    if [[ "$PLATFORM" != "android" ]]; then
        return
    fi

    echo "===== logcat after failed attempt: $test_name ====="
    bounded 60 adb logcat -d -t 400 || echo "logcat unavailable"
    echo "===== end logcat ====="
}

clean_data_directories() {
    if [[ "$REMOVE_DATA_DIRECTORY" != "Y" ]]; then
        return
    fi

    log "Cleaning app data..."

    if [[ "$PLATFORM" == "android" ]]; then
        # app_config.sh writes the real app id into android/app.properties, and wiping that
        # package would take a developer's own wallets with it. CI renames the app before
        # running, so only ever clear a package that was named for testing.
        if [[ "$ANDROID_APP_ID" != *".test_"* ]]; then
            error "Refusing to clear $ANDROID_APP_ID, it is not a test build. Rename the app first: printf 'id=com.cakewallet.test_local\\nname=local\\n' > android/app.properties"
        fi

        # pm clear resets the app to a fresh install so every suite starts from onboarding
        adb shell pm clear "$ANDROID_APP_ID" > /dev/null 2>&1 || log "pm clear skipped, $ANDROID_APP_ID not installed yet"
        return
    fi

    for dir in "${DATA_DIRS[@]}"; do
        if [[ -d "$dir" ]]; then
            rm -rf "$dir" || error "Failed to remove $dir"
        fi
    done
}

build_drive_command() {
    drive_command=(flutter drive --driver=test_driver/integration_test.dart --dart-define=CI_BUILD=true)

    if [[ -n "${FLUTTER_DEVICE:-}" ]]; then
        drive_command+=("-d" "$FLUTTER_DEVICE")
    fi

    if [[ -n "$PREBUILT_APK" ]]; then
        drive_command+=("--use-application-binary=$PREBUILT_APK")
    fi

    if [[ -n "$EXTRA_DART_DEFINES" ]]; then
        IFS=';' read -ra defines <<< "$EXTRA_DART_DEFINES"
        for define in "${defines[@]}"; do
            drive_command+=("--dart-define=$define")
        done
    fi

    # A wedged driver otherwise hangs the whole run, timeout is not available on stock
    # macOS so fall back to a perl alarm there
    if command -v timeout > /dev/null 2>&1; then
        drive_command=(timeout "$TEST_TIMEOUT" "${drive_command[@]}")
    elif command -v perl > /dev/null 2>&1; then
        drive_command=(perl -e 'alarm shift; exec @ARGV' "$TEST_TIMEOUT" "${drive_command[@]}")
    fi
}

run_test() {
    local test_file="$1"
    local test_name=$(basename "$test_file" .dart)
    local retry_count=0
    local void_attempts=0

    while (( retry_count <= RETRY_COUNT )); do
        log "Running test: $test_name (attempt $((retry_count + 1)))"

        # Clean data directories before each attempt so retries stay hermetic
        clean_data_directories

        local start_time=$(date +%s)
        local attempt_log
        attempt_log=$(mktemp)

        if "${drive_command[@]}" --target="$test_file" 2>&1 | tee "$attempt_log"; then
            local duration=$(( $(date +%s) - start_time ))

            log "PASS: $test_name ($(format_duration $duration))"
            passed_tests+=("$test_name|$duration")
            rm -f "$attempt_log"
            return 0
        else
            local duration=$(( $(date +%s) - start_time ))

            # A driver that never attaches never ran the test, that is an environment
            # problem rather than a test failure so it does not consume the real retry
            # flutter drive words this differently depending on how far the attach got,
            # so match every wording we have actually seen fail this way
            local attempt_was_void=N
            if grep -qE "unusually long time to connect to the VM|taking unusually long time to initialize|Service has disappeared|Flutter Driver extension is taking a long time to become available" "$attempt_log"; then
                attempt_was_void=Y
            fi

            rm -f "$attempt_log"

            log "FAIL: $test_name ($(format_duration $duration))"

            capture_failure_logcat "$test_name"

            if [[ "$attempt_was_void" == "Y" ]]; then
                total_void_attempts=$((total_void_attempts + 1))

                # An environment where the driver never attaches will not fix itself,
                # give up early instead of spending the whole job on dead attempts
                if (( total_void_attempts > MAX_TOTAL_VOID_ATTEMPTS )); then
                    error "The flutter driver failed to attach $total_void_attempts times, the emulator or adb is broken"
                    failed_tests+=("$test_name|$duration|void")
                    return 1
                fi
            fi

            if [[ "$attempt_was_void" == "Y" ]] && (( void_attempts < MAX_VOID_ATTEMPTS )); then
                log "Driver never attached to the app, retrying without spending a retry"
                void_attempts=$((void_attempts + 1))

                if ! restart_adb; then
                    error "Could not bring adb back, aborting this suite"
                    failed_tests+=("$test_name|$duration|void")
                    return 1
                fi

                sleep 5
            elif (( retry_count < RETRY_COUNT )); then
                log "Retrying test: $test_name"
                retry_count=$((retry_count + 1))
                sleep 5
            else
                # void means the driver never attached, so the suite never actually ran
                local fail_reason="test"
                [[ "$attempt_was_void" == "Y" ]] && fail_reason="void"

                failed_tests+=("$test_name|$duration|$fail_reason")
                return 1
            fi
        fi
    done
}

write_github_summary() {
    if [[ -z "${GITHUB_STEP_SUMMARY:-}" ]]; then
        return
    fi

    {
        echo "### Integration tests ($SUITE_DIR, tier: $TEST_TIER)"
        echo ""
        echo "| Suite | Result | Duration |"
        echo "|---|---|---|"
        for entry in "${passed_tests[@]+"${passed_tests[@]}"}"; do
            echo "| ${entry%%|*} | pass | $(format_duration "${entry##*|}") |"
        done
        for entry in "${failed_tests[@]+"${failed_tests[@]}"}"; do
            local rest="${entry#*|}"
            echo "| ${entry%%|*} | ${rest#*|} | $(format_duration "${rest%%|*}") |"
        done
    } >> "$GITHUB_STEP_SUMMARY"
}

# Machine readable counterpart to the github summary, for whoever has to build a message
# out of the run rather than read it.
write_summary_file() {
    if [[ -z "$SUMMARY_FILE" ]]; then
        return
    fi

    {
        echo "tier=$TEST_TIER"
        echo "total=${#targets[@]}"
        echo "passed=${#passed_tests[@]}"
        echo "failed=${#failed_tests[@]}"
        echo "duration=$1"
        for entry in "${passed_tests[@]+"${passed_tests[@]}"}"; do
            echo "pass=$entry"
        done
        for entry in "${failed_tests[@]+"${failed_tests[@]}"}"; do
            echo "fail=$entry"
        done
    } > "$SUMMARY_FILE"
}

main() {
    log "Starting integration test runner"

    local search_dir="$SUITE_DIR"
    if [[ "$TEST_TIER" != "all" ]]; then
        search_dir="$SUITE_DIR/$TEST_TIER"
    fi

    if [[ -f "$SUITE_DIR" ]]; then
        search_dir="$SUITE_DIR"
    elif [[ ! -d "$search_dir" ]]; then
        error "Suite directory not found: $search_dir"
        exit 1
    fi

    resolve_platform
    resolve_android_app_id
    build_drive_command

    log "Configuration: SUITE_DIR=$search_dir PLATFORM=$PLATFORM RETRY_COUNT=$RETRY_COUNT"

    # Only *_test.dart files are runnable suites, helpers and templates are never picked up
    if [[ -f "$search_dir" ]]; then
        targets+=("$search_dir")
    else
        while IFS= read -r -d $'\0' file; do
            targets+=("$file")
        done < <(find "$search_dir" -name "*_test.dart" -type f -print0 | sort -z)
    fi

    if (( ${#targets[@]} == 0 )); then
        error "No test files found in $search_dir"
        exit 1
    fi

    log "Found ${#targets[@]} test files"

    local overall_start_time=$(date +%s)

    # A failing suite must not stop the remaining suites, failures are collected for the summary
    for target in "${targets[@]}"; do
        run_test "$target" || true
    done

    local total_duration=$(( $(date +%s) - overall_start_time ))

    echo -e "\n===== Test Summary ====="
    echo "Total tests: ${#targets[@]}"
    echo "Passed: ${#passed_tests[@]}"
    echo "Failed: ${#failed_tests[@]}"
    echo "Total duration: $(format_duration $total_duration)"

    if (( ${#passed_tests[@]} > 0 )); then
        echo -e "\nPassed Tests:"
        for entry in "${passed_tests[@]}"; do
            echo "  - ${entry%%|*} ($(format_duration "${entry##*|}"))"
        done
    fi

    write_github_summary
    write_summary_file "$total_duration"

    if (( ${#failed_tests[@]} > 0 )); then
        echo -e "\nFailed Tests:"
        local rest
        for entry in "${failed_tests[@]}"; do
            rest="${entry#*|}"
            echo "  - ${entry%%|*} ($(format_duration "${rest%%|*}"), ${rest#*|})"
        done
        exit 1
    fi

    echo -e "\nAll tests passed successfully!"
}

main "$@"
