name: cw_tari
description: "A CakeWallet Package for Tari"
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cw_core:
    path: ../cw_core
  hive: ^2.2.3
  mobx: ^2.0.7+4
  tari:
    path: ../../tari_dart/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.0.7
  mockito: ^5.4.5

flutter:
