import 'package:cw_core/crypto_currency.dart';
import 'package:cw_core/currency_groups.dart';
import 'package:cw_core/erc20_token.dart';

class RobinhoodTokens {
  static List<Erc20Token> get tokens {
    final tokens = [
      Erc20Token(
        name: "Global Dollar",
        symbol: "USDG",
        contractAddress: "0x5fc5360d0400a0fd4f2af552add042d716f1d168",
        decimal: 6,
        enabled: true,
        iconPath: "assets/images/usdg_icon.png",
      ),
      Erc20Token(
        name: "Ethena USDe",
        symbol: "USDe",
        contractAddress: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34",
        decimal: 18,
        enabled: true,
      ),
      Erc20Token(
        name: "WETH",
        symbol: "WETH",
        contractAddress: "0x0bd7d308f8e1639fab988df18a8011f41eacad73",
        decimal: 18,
        enabled: true,
      ),
      Erc20Token(
        name: "Apple",
        symbol: "AAPL",
        contractAddress: "0xaf3d76f1834a1d425780943c99ea8a608f8a93f9",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/apple.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "AMD",
        symbol: "AMD",
        contractAddress: "0x86923f96303d656e4aa86d9d42d1e57ad2023fdc",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/amd.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Amazon",
        symbol: "AMZN",
        contractAddress: "0x12f190a9f9d7d37a250758b26824b97ce941bf54",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/amznx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "ASML Holding NV",
        symbol: "ASML",
        contractAddress: "0x47f93d52cbec7c6d2cfc080e154002370a60daea",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/asml.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Broadcom",
        symbol: "AVGO",
        contractAddress: "0x156e175dd063a8ce274c50654ef40e0032b3fbcf",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/avgox.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Alibaba",
        symbol: "BABA",
        contractAddress: "0xad25ac6c84d497db898fa1e8387bf6af3532a1c4",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/baba.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Coinbase",
        symbol: "COIN",
        contractAddress: "0x6330d8c3178a418788df01a47479c0ce7ccf450b",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/coinx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Costco",
        symbol: "COST",
        contractAddress: "0x4ea005168d7f09a7a0ba9d1def21a479950e44c2",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/cost.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Circle Internet Group",
        symbol: "CRCL",
        contractAddress: "0xdf0992e440dd0be65bd8439b609d6d4366bf1cb5",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/crclx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Datadog",
        symbol: "DDOG",
        contractAddress: "0x27c99fbde9d0d2aa4f4bfb4943f237843ddf6958",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/ddog.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Dell",
        symbol: "DELL",
        contractAddress: "0x941ae714ec6d8130c7b75d67160ca08f1e7d11dd",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/dell.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Ford Motor",
        symbol: "F",
        contractAddress: "0x25c288e6d899b9bc30160965ad9644c67e73be0c",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/f.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "GameStop",
        symbol: "GME",
        contractAddress: "0x1b0e319c6a659f002271b69db8a7df2f911c153e",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/gmex.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Alphabet Class A",
        symbol: "GOOGL",
        contractAddress: "0x2e0847e8910a9732eb3fb1bb4b70a580adad4fe3",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/googlx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Intel",
        symbol: "INTC",
        contractAddress: "0xc72b96e0e48ecd4dc75e1e45396e26300bc39681",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/intcx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Intuit",
        symbol: "INTU",
        contractAddress: "0x56d23bee5f41a7120170b0c603dae30128e460e9",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/intu.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Eli Lilly",
        symbol: "LLY",
        contractAddress: "0x8005d266423c7ea827372c9c864491e5786600ea",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/llyx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Lululemon",
        symbol: "LULU",
        contractAddress: "0x4e62068525ab11fe768e29dfd00ef909b9803016",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/lulu.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Meta Platforms",
        symbol: "META",
        contractAddress: "0xc0d6457c16cc70d6790dd43521c899c87ce02f35",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/metax.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Marvell Technology",
        symbol: "MRVL",
        contractAddress: "0x62fd0668e10d8b72339be2dcf7643001688ff13b",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/mrvlx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Microsoft",
        symbol: "MSFT",
        contractAddress: "0xe93237c50d904957cf27e7b1133b510c669c2e74",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/msftx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Strategy Inc.",
        symbol: "MSTR",
        contractAddress: "0xec262a75e413fafd0df80480274532c79d42da09",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/mstrx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Micron Technology",
        symbol: "MU",
        contractAddress: "0xff080c8ce2e5feadaca0da81314ae59d232d4afd",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/mu.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Netflix",
        symbol: "NFLX",
        contractAddress: "0xe0444ef8bf4ed74f74fd73686e2ddf4c1c5591e8",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/nflxx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Nu",
        symbol: "NU",
        contractAddress: "0x408c14038a04f7bd235329e26d2bf569ee20e250",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/nu.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "NVIDIA",
        symbol: "NVDA",
        contractAddress: "0xd0601ce157db5bdc3162bbac2a2c8af5320d9eec",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/nvdax.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Oracle",
        symbol: "ORCL",
        contractAddress: "0xb0992820e760d836549ba69bc7598b4af75dee03",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/orclx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Palantir Technologies",
        symbol: "PLTR",
        contractAddress: "0x894e1ec2d74ffe5aef8dc8a9e84686accb964f2a",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/pltrx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Qualcomm",
        symbol: "QCOM",
        contractAddress: "0x0f17206447090e464c277571124dd2688e48aea9",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/qcom.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Invesco QQQ",
        symbol: "QQQ",
        contractAddress: "0xd5f3879160bc7c32ebb4dc785f8a4f505888de68",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/qqqx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Rivian Automotive",
        symbol: "RIVN",
        contractAddress: "0xb1bf26c1d20ff267a4f93550d1e0d06ac40a114b",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/rivn.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Shopify",
        symbol: "SHOP",
        contractAddress: "0xf53f66751b1eff985311b693531e3290f600c410",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/shop.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "SoFi Technologies",
        symbol: "SOFI",
        contractAddress: "0x98e75885157c80992a8d41b696d8c9c6fb30a926",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/sofi.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "SPDR S&P 500 ETF Trust",
        symbol: "SPY",
        contractAddress: "0x117cc2133c37b721f49de2a7a74833232b3b4c0c",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/spyx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Tesla",
        symbol: "TSLA",
        contractAddress: "0x322f0929c4625ed5bad873c95208d54e1c003b2d",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/tslax.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Taiwan Semiconductor Manufacturing",
        symbol: "TSM",
        contractAddress: "0x58ffe4a942d3885baa22d7520691f611ef09e7aa",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/tsm.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Take-Two Interactive Software",
        symbol: "TTWO",
        contractAddress: "0x5e81213613b6b86eab4c6c50d718d34359459786",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/ttwo.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "UPS",
        symbol: "UPS",
        contractAddress: "0xf23250dac154d05bb671cb0d0ebef3c635c79ce2",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/ups.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "Workday",
        symbol: "WDAY",
        contractAddress: "0x82da4646242e1d962e96e932269dc644c94a9caa",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/wday.png",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
      Erc20Token(
        name: "ExxonMobil Holdings Corporation",
        symbol: "XOM",
        contractAddress: "0xf9b46d3d1b22199d4d1025a9cedb540a33f1a2d5",
        decimal: 18,
        enabled: false,
        iconPath: "assets/images/stocks/xomx.webp",
        groups: const {CurrencyGroups.tokenizedStock},
      ),
    ];

    return tokens.map((token) {
      String? iconPath;
      if (token.iconPath?.isEmpty ?? true) {
        try {
          iconPath = CryptoCurrency.all
              .firstWhere((element) => element.title.toUpperCase() == token.symbol.toUpperCase())
              .iconPath;
        } catch (_) {}
      } else {
        iconPath = token.iconPath;
      }

      return Erc20Token.copyWith(token, icon: iconPath, tag: 'ROB');
    }).toList();
  }
}
