name: cw_keychain

environment:
  sdk: ^3.11.5
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: 27.3.0
  build_runner: ^2.15.0
  pigeon_generator: 3.1.1
dependency_overrides:
  pigeon: 27.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cakewallet.cw_keychain
        pluginClass: CwKeychainPlugin
      ios:
        pluginClass: CwKeychainPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: CwKeychainPlugin
        sharedDarwinSource: true
