// This file will be auto-generated by ffigen.
// Run: flutter pub run ffigen
//
// Placeholder to allow imports to compile.
// After building the Rust library and running ffigen, this file will be replaced
// with the actual FFI bindings.

import 'dart:ffi';

// Opaque wallet handle struct
final class WalletHandle extends Opaque {}

// Placeholder bindings class
// This will be replaced by ffigen-generated code
class MinotariWalletFfiBindings {
  MinotariWalletFfiBindings(DynamicLibrary dynamicLibrary);

  void minotari_init_logging() {
    throw UnimplementedError('FFI bindings not yet generated. Run: flutter pub run ffigen');
  }

  Pointer<WalletHandle> minotari_wallet_create_from_mnemonic(
    Pointer<Char> mnemonic,
    Pointer<Char> dataPath,
    Pointer<Char> passphrase,
    Pointer<Pointer<Char>> errorOut,
  ) {
    throw UnimplementedError('FFI bindings not yet generated');
  }

  Pointer<WalletHandle> minotari_wallet_restore(
    Pointer<Char> mnemonic,
    Pointer<Char> dataPath,
    Pointer<Char> passphrase,
    Pointer<Pointer<Char>> errorOut,
  ) {
    throw UnimplementedError('FFI bindings not yet generated');
  }

  Pointer<Char> minotari_wallet_get_address(
    Pointer<WalletHandle> handle,
    Pointer<Pointer<Char>> errorOut,
  ) {
    throw UnimplementedError('FFI bindings not yet generated');
  }

  int minotari_wallet_get_balance(
    Pointer<WalletHandle> handle,
    Pointer<Uint64> availableOut,
    Pointer<Uint64> pendingIncomingOut,
    Pointer<Uint64> pendingOutgoingOut,
    Pointer<Pointer<Char>> errorOut,
  ) {
    throw UnimplementedError('FFI bindings not yet generated');
  }

  int minotari_wallet_sync(
    Pointer<WalletHandle> handle,
    Pointer<Char> baseNodeAddress,
    Pointer<Pointer<Char>> errorOut,
  ) {
    throw UnimplementedError('FFI bindings not yet generated');
  }

  void minotari_wallet_free(Pointer<WalletHandle> handle) {
    throw UnimplementedError('FFI bindings not yet generated');
  }

  void minotari_string_free(Pointer<Char> s) {
    throw UnimplementedError('FFI bindings not yet generated');
  }
}
