/// Contents of this file is autogenerated, avoid editing manually 
import 'package:cake_wallet/migrations/migration_v1.dart';
import 'package:cake_wallet/migrations/migration_v2.dart';
import 'package:cake_wallet/migrations/migration_v3.dart';
import 'package:cake_wallet/migrations/migration_v4.dart';
import 'package:cake_wallet/migrations/migration_v5.dart';
import 'package:cake_wallet/migrations/migration_v6.dart';
import 'package:cake_wallet/migrations/migration_v7.dart';
import 'package:cake_wallet/migrations/migration_v8.dart';
import 'package:cake_wallet/migrations/migration_v9.dart';
import 'package:cake_wallet/migrations/migration_v10.dart';
import 'package:cake_wallet/migrations/migration_v11.dart';
import 'package:cake_wallet/migrations/migration_v12.dart';
import 'package:cake_wallet/migrations/migration_v13.dart';
import 'package:cake_wallet/migrations/migration_v14.dart';
import 'package:cake_wallet/migrations/migration_v15.dart';

/// Switch for versions of migrations to run 
Future<void> switchMigrations(int version) async {
    switch (version) {
      
      case 1:
        await MigrationV1.run();
        break;
      case 2:
        await MigrationV2.run();
        break;
      case 3:
        await MigrationV3.run();
        break;
      case 4:
        await MigrationV4.run();
        break;
      case 5:
        await MigrationV5.run();
        break;
      case 6:
        await MigrationV6.run();
        break;
      case 7:
        await MigrationV7.run();
        break;
      case 8:
        await MigrationV8.run();
        break;
      case 9:
        await MigrationV9.run();
        break;
      case 10:
        await MigrationV10.run();
        break;
      case 11:
        await MigrationV11.run();
        break;
      case 12:
        await MigrationV12.run();
        break;
      case 13:
        await MigrationV13.run();
        break;
      case 14:
        await MigrationV14.run();
        break;
      case 15:
        await MigrationV15.run();
        break;
      default:
    }
  }