import 'package:cw_core/crypto_currency.dart';
import 'package:cw_core/spl_token.dart';

class DefaultSPLTokens {
  final List<SPLToken> _defaultTokens = [
    SPLToken(
      name: 'USDT Tether',
      symbol: 'USDT',
      mintAddress: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
      decimal: 6,
      mint: 'usdtsol',
      enabled: true,
    ),
    SPLToken(
      name: 'USD Coin',
      symbol: 'USDC',
      mintAddress: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      decimal: 6,
      mint: 'usdcsol',
      enabled: true,
    ),
    SPLToken(
      name: 'Bonk',
      symbol: 'Bonk',
      mintAddress: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
      decimal: 5,
      mint: 'Bonk',
      iconPath: 'assets/images/bonk_icon.png',
      enabled: false,
    ),
    SPLToken(
      name: 'Raydium',
      symbol: 'RAY',
      mintAddress: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
      decimal: 6,
      mint: 'ray',
      iconPath: 'assets/images/ray_icon.png',
      enabled: false,
    ),
    SPLToken(
      name: 'Wrapped Ethereum (Sollet)',
      symbol: 'soETH',
      mintAddress: '2FPyTwcZLUg1MDrwsyoP4D6s1tM7hAkHYRjkNb5w6Pxk',
      decimal: 6,
      mint: 'soEth',
      iconPath: 'assets/images/eth_icon.png',
      enabled: false,
    ),
    SPLToken(
      name: 'Wrapped SOL',
      symbol: 'WSOL',
      mintAddress: 'So11111111111111111111111111111111111111112',
      decimal: 9,
      mint: 'WSOL',
      iconPath: 'assets/images/sol_icon.png',
      enabled: false,
    ),
    SPLToken(
      name: 'Wrapped Bitcoin (Sollet)',
      symbol: 'BTC',
      mintAddress: '9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E',
      decimal: 6,
      mint: 'btcsol',
      iconPath: 'assets/images/btc.png',
      enabled: false,
    ),
    SPLToken(
      name: 'Helium Network Token',
      symbol: 'HNT',
      mintAddress: 'hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux',
      decimal: 8,
      mint: 'hnt',
      iconPath: 'assets/images/hnt_icon.png',
      enabled: false,
    ),
    SPLToken(
      name: 'Pyth Network',
      symbol: 'PYTH',
      mintAddress: 'HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3',
      decimal: 6,
      mint: 'pyth',
      enabled: false,
    ),
    SPLToken(
      name: 'GMT',
      symbol: 'GMT',
      mintAddress: '7i5KKsX2weiTkry7jA4ZwSuXGhs5eJBEjY8vVxR4pfRx',
      decimal: 6,
      mint: 'ray',
      iconPath: 'assets/images/gmt_icon.png',
      enabled: false,
    ),
    SPLToken(
      name: 'AvocadoCoin',
      symbol: 'AVDO',
      mintAddress: 'EE5L8cMU4itTsCSuor7NLK6RZx6JhsBe8GGV3oaAHm3P',
      decimal: 8,
      mint: 'avdo',
      iconPath: 'assets/images/avdo_icon.png',
      enabled: false,
    ),
    // SPLToken(
    //     name: 'Abbott xStock',
    //     symbol: 'ABTx',
    //     mintAddress: 'XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7',
    //     decimal: 8,
    //     mint: 'abtx',
    //     enabled: false),
    // SPLToken(
    //     name: 'AbbVie xStock',
    //     symbol: 'ABBVx',
    //     mintAddress: 'XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie',
    //     decimal: 8,
    //     mint: 'abbvx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Accenture xStock',
    //     symbol: 'ACNx',
    //     mintAddress: 'Xs5UJzmCRQ8DWZjskExdSQDnbE6iLkRu2jjrRAB1JSU',
    //     decimal: 8,
    //     mint: 'acnx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Alphabet xStock',
    //     symbol: 'GOOGLx',
    //     mintAddress: 'XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN',
    //     decimal: 8,
    //     mint: 'googlx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Amazon xStock',
    //     symbol: 'AMZNx',
    //     mintAddress: 'Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg',
    //     decimal: 8,
    //     mint: 'amznx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Amber xStock',
    //     symbol: 'AMBRx',
    //     mintAddress: 'XsaQTCgebC2KPbf27KUhdv5JFvHhQ4GDAPURwrEhAzb',
    //     decimal: 8,
    //     mint: 'ambrx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Apple xStock',
    //     symbol: 'AAPLx',
    //     mintAddress: 'XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp',
    //     decimal: 8,
    //     mint: 'aaplx',
    //     enabled: false),
    // SPLToken(
    //     name: 'AppLovin xStock',
    //     symbol: 'APPx',
    //     mintAddress: 'XsPdAVBi8Zc1xvv53k4JcMrQaEDTgkGqKYeh7AYgPHV',
    //     decimal: 8,
    //     mint: 'appx',
    //     enabled: false),
    // SPLToken(
    //     name: 'AstraZeneca xStock',
    //     symbol: 'AZNx',
    //     mintAddress: 'Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU',
    //     decimal: 8,
    //     mint: 'aznx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Bank of America xStock',
    //     symbol: 'BACx',
    //     mintAddress: 'XswsQk4duEQmCbGzfqUUWYmi7pV7xpJ9eEmLHXCaEQP',
    //     decimal: 8,
    //     mint: 'bacx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Berkshire Hathaway xStock',
    //     symbol: 'BRK.Bx',
    //     mintAddress: 'Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x',
    //     decimal: 8,
    //     mint: 'brkbx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Broadcom xStock',
    //     symbol: 'AVGOx',
    //     mintAddress: 'XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo',
    //     decimal: 8,
    //     mint: 'avgox',
    //     enabled: false),
    // SPLToken(
    //     name: 'Chevron xStock',
    //     symbol: 'CVXx',
    //     mintAddress: 'XsNNMt7WTNA2sV3jrb1NNfNgapxRF5i4i6GcnTRRHts',
    //     decimal: 8,
    //     mint: 'cvxx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Circle xStock',
    //     symbol: 'CRCLx',
    //     mintAddress: 'XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1',
    //     decimal: 8,
    //     mint: 'crclx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Cisco xStock',
    //     symbol: 'CSCOx',
    //     mintAddress: 'Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf',
    //     decimal: 8,
    //     mint: 'cscx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Coca-Cola xStock',
    //     symbol: 'KOx',
    //     mintAddress: 'XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ',
    //     decimal: 8,
    //     mint: 'kox',
    //     enabled: false),
    // SPLToken(
    //     name: 'Coinbase xStock',
    //     symbol: 'COINx',
    //     mintAddress: 'Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu',
    //     decimal: 8,
    //     mint: 'coinx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Comcast xStock',
    //     symbol: 'CMCSAx',
    //     mintAddress: 'XsvKCaNsxg2GN8jjUmq71qukMJr7Q1c5R2Mk9P8kcS8',
    //     decimal: 8,
    //     mint: 'cmcsax',
    //     enabled: false),
    // SPLToken(
    //     name: 'CrowdStrike xStock',
    //     symbol: 'CRWDx',
    //     mintAddress: 'Xs7xXqkcK7K8urEqGg52SECi79dRp2cEKKuYjUePYDw',
    //     decimal: 8,
    //     mint: 'crwdx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Danaher xStock',
    //     symbol: 'DHRx',
    //     mintAddress: 'Xseo8tgCZfkHxWS9xbFYeKFyMSbWEvZGFV1Gh53GtCV',
    //     decimal: 8,
    //     mint: 'dhrx',
    //     enabled: false),
    // SPLToken(
    //     name: 'DFDV xStock',
    //     symbol: 'DFDVx',
    //     mintAddress: 'Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy',
    //     decimal: 8,
    //     mint: 'dfdvx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Eli Lilly xStock',
    //     symbol: 'LLYx',
    //     mintAddress: 'Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH',
    //     decimal: 8,
    //     mint: 'llyx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Exxon Mobil xStock',
    //     symbol: 'XOMx',
    //     mintAddress: 'XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh',
    //     decimal: 8,
    //     mint: 'xomx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Gamestop xStock',
    //     symbol: 'GMEx',
    //     mintAddress: 'Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc',
    //     decimal: 8,
    //     mint: 'gmex',
    //     enabled: false),
    // SPLToken(
    //     name: 'Gold xStock',
    //     symbol: 'GLDx',
    //     mintAddress: 'Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re',
    //     decimal: 8,
    //     mint: 'gldx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Goldman Sachs xStock',
    //     symbol: 'GSx',
    //     mintAddress: 'XsgaUyp4jd1fNBCxgtTKkW64xnnhQcvgaxzsbAq5ZD1',
    //     decimal: 8,
    //     mint: 'gsx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Home Depot xStock',
    //     symbol: 'HDx',
    //     mintAddress: 'XszjVtyhowGjSC5odCqBpW1CtXXwXjYokymrk7fGKD3',
    //     decimal: 8,
    //     mint: 'hdx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Honeywell xStock',
    //     symbol: 'HONx',
    //     mintAddress: 'XsRbLZthfABAPAfumWNEJhPyiKDW6TvDVeAeW7oKqA2',
    //     decimal: 8,
    //     mint: 'honx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Intel xStock',
    //     symbol: 'INTCx',
    //     mintAddress: 'XshPgPdXFRWB8tP1j82rebb2Q9rPgGX37RuqzohmArM',
    //     decimal: 8,
    //     mint: 'intcx',
    //     enabled: false),
    // SPLToken(
    //     name: 'International Business Machines xStock',
    //     symbol: 'IBMx',
    //     mintAddress: 'XspwhyYPdWVM8XBHZnpS9hgyag9MKjLRyE3tVfmCbSr',
    //     decimal: 8,
    //     mint: 'ibmx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Johnson & Johnson xStock',
    //     symbol: 'JNJx',
    //     mintAddress: 'XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn',
    //     decimal: 8,
    //     mint: 'jnjx',
    //     enabled: false),
    // SPLToken(
    //     name: 'JPMorgan Chase xStock',
    //     symbol: 'JPMx',
    //     mintAddress: 'XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C',
    //     decimal: 8,
    //     mint: 'jpmx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Linde xStock',
    //     symbol: 'LINx',
    //     mintAddress: 'XsSr8anD1hkvNMu8XQiVcmiaTP7XGvYu7Q58LdmtE8Z',
    //     decimal: 8,
    //     mint: 'linx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Marvell xStock',
    //     symbol: 'MRVLx',
    //     mintAddress: 'XsuxRGDzbLjnJ72v74b7p9VY6N66uYgTCyfwwRjVCJA',
    //     decimal: 8,
    //     mint: 'mrvlx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Mastercard xStock',
    //     symbol: 'MAx',
    //     mintAddress: 'XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC',
    //     decimal: 8,
    //     mint: 'max',
    //     enabled: false),
    // SPLToken(
    //     name: 'McDonald\'s xStock',
    //     symbol: 'MCDx',
    //     mintAddress: 'XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2',
    //     decimal: 8,
    //     mint: 'mcdx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Medtronic xStock',
    //     symbol: 'MDTx',
    //     mintAddress: 'XsDgw22qRLTv5Uwuzn6T63cW69exG41T6gwQhEK22u2',
    //     decimal: 8,
    //     mint: 'mdtx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Merck xStock',
    //     symbol: 'MRKx',
    //     mintAddress: 'XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X',
    //     decimal: 8,
    //     mint: 'mrkx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Meta xStock',
    //     symbol: 'METAx',
    //     mintAddress: 'Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu',
    //     decimal: 8,
    //     mint: 'metax',
    //     enabled: false),
    // SPLToken(
    //     name: 'Microsoft xStock',
    //     symbol: 'MSFTx',
    //     mintAddress: 'XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX',
    //     decimal: 8,
    //     mint: 'msftx',
    //     enabled: false),
    // SPLToken(
    //     name: 'MicroStrategy xStock',
    //     symbol: 'MSTRx',
    //     mintAddress: 'XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ',
    //     decimal: 8,
    //     mint: 'mstrx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Nasdaq xStock',
    //     symbol: 'QQQx',
    //     mintAddress: 'Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ',
    //     decimal: 8,
    //     mint: 'qqqx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Netflix xStock',
    //     symbol: 'NFLXx',
    //     mintAddress: 'XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL',
    //     decimal: 8,
    //     mint: 'nflxx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Novo Nordisk xStock',
    //     symbol: 'NVOx',
    //     mintAddress: 'XsfAzPzYrYjd4Dpa9BU3cusBsvWfVB9gBcyGC87S57n',
    //     decimal: 8,
    //     mint: 'nvox',
    //     enabled: false),
    // SPLToken(
    //     name: 'NVIDIA xStock',
    //     symbol: 'NVDAx',
    //     mintAddress: 'Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh',
    //     decimal: 8,
    //     mint: 'nvdax',
    //     enabled: false),
    // SPLToken(
    //     name: 'OPEN xStock',
    //     symbol: 'OPENx',
    //     mintAddress: 'XsGtpmjhmC8kyjVSWL4VicGu36ceq9u55PTgF8bhGv6',
    //     decimal: 8,
    //     mint: 'openx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Oracle xStock',
    //     symbol: 'ORCLx',
    //     mintAddress: 'XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL',
    //     decimal: 8,
    //     mint: 'orclx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Palantir xStock',
    //     symbol: 'PLTRx',
    //     mintAddress: 'XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4',
    //     decimal: 8,
    //     mint: 'pltrx',
    //     enabled: false),
    // SPLToken(
    //     name: 'PepsiCo xStock',
    //     symbol: 'PEPx',
    //     mintAddress: 'Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF',
    //     decimal: 8,
    //     mint: 'pepx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Pfizer xStock',
    //     symbol: 'PFEx',
    //     mintAddress: 'XsAtbqkAP1HJxy7hFDeq7ok6yM43DQ9mQ1Rh861X8rw',
    //     decimal: 8,
    //     mint: 'pfex',
    //     enabled: false),
    // SPLToken(
    //     name: 'Philip Morris xStock',
    //     symbol: 'PMx',
    //     mintAddress: 'Xsba6tUnSjDae2VcopDB6FGGDaxRrewFCDa5hKn5vT3',
    //     decimal: 8,
    //     mint: 'pmx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Procter & Gamble xStock',
    //     symbol: 'PGx',
    //     mintAddress: 'XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV',
    //     decimal: 8,
    //     mint: 'pgx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Robinhood xStock',
    //     symbol: 'HOODx',
    //     mintAddress: 'XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg',
    //     decimal: 8,
    //     mint: 'hoodx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Salesforce xStock',
    //     symbol: 'CRMx',
    //     mintAddress: 'XsczbcQ3zfcgAEt9qHQES8pxKAVG5rujPSHQEXi4kaN',
    //     decimal: 8,
    //     mint: 'crmx',
    //     enabled: false),
    // SPLToken(
    //     name: 'SP500 xStock',
    //     symbol: 'SPYx',
    //     mintAddress: 'XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W',
    //     decimal: 8,
    //     mint: 'spyx',
    //     enabled: false),
    // SPLToken(
    //     name: 'TBLL xStock',
    //     symbol: 'TBLLx',
    //     mintAddress: 'XsqBC5tcVQLYt8wqGCHRnAUUecbRYXoJCReD6w7QEKp',
    //     decimal: 8,
    //     mint: 'tbllx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Tesla xStock',
    //     symbol: 'TSLAx',
    //     mintAddress: 'XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB',
    //     decimal: 8,
    //     mint: 'tslax',
    //     enabled: false),
    // SPLToken(
    //     name: 'Thermo Fisher xStock',
    //     symbol: 'TMOx',
    //     mintAddress: 'Xs8drBWy3Sd5QY3aifG9kt9KFs2K3PGZmx7jWrsrk57',
    //     decimal: 8,
    //     mint: 'tmox',
    //     enabled: false),
    // SPLToken(
    //     name: 'TQQQ xStock',
    //     symbol: 'TQQQx',
    //     mintAddress: 'XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc',
    //     decimal: 8,
    //     mint: 'tqqqx',
    //     enabled: false),
    // SPLToken(
    //     name: 'UnitedHealth xStock',
    //     symbol: 'UNHx',
    //     mintAddress: 'XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe',
    //     decimal: 8,
    //     mint: 'unhx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Vanguard xStock',
    //     symbol: 'VTIx',
    //     mintAddress: 'XsssYEQjzxBCFgvYFFNuhJFBeHNdLWYeUSP8F45cDr9',
    //     decimal: 8,
    //     mint: 'vtix',
    //     enabled: false),
    // SPLToken(
    //     name: 'Visa xStock',
    //     symbol: 'Vx',
    //     mintAddress: 'XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p',
    //     decimal: 8,
    //     mint: 'vx',
    //     enabled: false),
    // SPLToken(
    //     name: 'Walmart xStock',
    //     symbol: 'WMTx',
    //     mintAddress: 'Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci',
    //     decimal: 8,
    //     mint: 'wmtx',
    //     enabled: false),

  ];

  List<SPLToken> get initialSPLTokens => _defaultTokens.map((token) {
        String? iconPath;
        if (token.iconPath != null) return token;

        try {
          iconPath = CryptoCurrency.all
              .firstWhere((element) => element.title.toUpperCase() == token.symbol.toUpperCase())
              .iconPath;
        } catch (_) {}

        return SPLToken.copyWith(token, iconPath, 'SOL');
      }).toList();
}
