name: cw_starknet
description: Starknet wallet implementation for Cake Wallet.
version: 0.0.1
publish_to: none
homepage: https://cakewallet.com

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cw_core:
    path: ../cw_core
  starknet:
    path: /Users/adrienlacombe/ws/starknet-dart
  http: ^1.1.0
  hive: ^2.2.3
  bip39: ^1.0.6
  mobx: ^2.3.0+1
  shared_preferences: ^2.0.15
  hex: ^0.2.0
  pointycastle: ^3.9.1
  crypto: ^3.0.5
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.0.7

dependency_overrides:
  watcher: ^1.1.0

flutter:
