// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `actual_fee_from_receipt`, `biguint_to_uint256_words`, `derive_account_inner`, `derive_private_key_from_mnemonic`, `felt_to_biguint`, `felt_to_hex`, `fetch_block_timestamp`, `fetch_paginated_transfer_events`, `fetch_transaction_fee`, `format_account_error`, `format_account_factory_error`, `format_provider_error`, `format_starknet_error`, `from_result`, `from_result`, `from_result`, `from_result`, `from_result`, `from_result`, `is_account_deployed_with_provider`, `make_provider`, `normalize_hex`, `parse_chain_id`, `parse_decimal_biguint`, `parse_felt_hex`, `parse_private_key`, `parse_transfer_event`, `run_async`, `sign_message_hash_inner`, `split_result`, `transfer_call`, `transfer_calldata`, `uint256_from_call_result`, `uint256_from_words`, `validate_private_key`, `verify_message_hash_signature_inner`, `wait_for_transaction`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TransferEventRecord`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<DerivedAccountDataResponse> deriveAccount(
        {String? mnemonic,
        String? passphrase,
        String? privateKeyHex,
        required String accountClassHashHex}) =>
    RustLib.instance.api.crateApiStarknetDeriveAccount(
        mnemonic: mnemonic,
        passphrase: passphrase,
        privateKeyHex: privateKeyHex,
        accountClassHashHex: accountClassHashHex);

Future<StringResponse> getTokenBalance(
        {required String nodeUrl,
        required String accountAddressHex,
        required String tokenAddressHex}) =>
    RustLib.instance.api.crateApiStarknetGetTokenBalance(
        nodeUrl: nodeUrl,
        accountAddressHex: accountAddressHex,
        tokenAddressHex: tokenAddressHex);

Future<BoolResponse> isAccountDeployed(
        {required String nodeUrl, required String accountAddressHex}) =>
    RustLib.instance.api.crateApiStarknetIsAccountDeployed(
        nodeUrl: nodeUrl, accountAddressHex: accountAddressHex);

Future<StringResponse> estimateTransferFee(
        {required String nodeUrl,
        required String privateKeyHex,
        required String accountAddressHex,
        required String recipientAddressHex,
        required String tokenAddressHex,
        required String amountWei,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetEstimateTransferFee(
        nodeUrl: nodeUrl,
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        recipientAddressHex: recipientAddressHex,
        tokenAddressHex: tokenAddressHex,
        amountWei: amountWei,
        chainIdHex: chainIdHex);

Future<StringResponse> estimateStandardTransferFee(
        {required String nodeUrl,
        required String privateKeyHex,
        required String accountAddressHex,
        required String tokenAddressHex,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetEstimateStandardTransferFee(
        nodeUrl: nodeUrl,
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        tokenAddressHex: tokenAddressHex,
        chainIdHex: chainIdHex);

Future<StringResponse> sendTransfer(
        {required String nodeUrl,
        required String privateKeyHex,
        required String accountAddressHex,
        required String recipientAddressHex,
        required String tokenAddressHex,
        required String amountWei,
        required String accountClassHashHex,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetSendTransfer(
        nodeUrl: nodeUrl,
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        recipientAddressHex: recipientAddressHex,
        tokenAddressHex: tokenAddressHex,
        amountWei: amountWei,
        accountClassHashHex: accountClassHashHex,
        chainIdHex: chainIdHex);

Future<TransferHistoryResponse> fetchTransferHistory(
        {required String nodeUrl,
        required String accountAddressHex,
        required String tokenAddressHex,
        required String tokenSymbol,
        PlatformInt64? fromBlock,
        int? maxPages}) =>
    RustLib.instance.api.crateApiStarknetFetchTransferHistory(
        nodeUrl: nodeUrl,
        accountAddressHex: accountAddressHex,
        tokenAddressHex: tokenAddressHex,
        tokenSymbol: tokenSymbol,
        fromBlock: fromBlock,
        maxPages: maxPages);

Future<I64Response> getBlockNumber({required String nodeUrl}) =>
    RustLib.instance.api.crateApiStarknetGetBlockNumber(nodeUrl: nodeUrl);

Future<StarknetSignatureDataResponse> signMessageHash(
        {required String privateKeyHex, required String messageHashHex}) =>
    RustLib.instance.api.crateApiStarknetSignMessageHash(
        privateKeyHex: privateKeyHex, messageHashHex: messageHashHex);

Future<BoolResponse> verifyMessageHashSignature(
        {required String publicKeyHex,
        required String messageHashHex,
        required String rHex,
        required String sHex}) =>
    RustLib.instance.api.crateApiStarknetVerifyMessageHashSignature(
        publicKeyHex: publicKeyHex,
        messageHashHex: messageHashHex,
        rHex: rHex,
        sHex: sHex);

class BoolResponse {
  final bool? value;
  final String? error;

  const BoolResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoolResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class DerivedAccountData {
  final String privateKeyHex;
  final String publicKeyHex;
  final String accountAddressHex;

  const DerivedAccountData({
    required this.privateKeyHex,
    required this.publicKeyHex,
    required this.accountAddressHex,
  });

  @override
  int get hashCode =>
      privateKeyHex.hashCode ^
      publicKeyHex.hashCode ^
      accountAddressHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DerivedAccountData &&
          runtimeType == other.runtimeType &&
          privateKeyHex == other.privateKeyHex &&
          publicKeyHex == other.publicKeyHex &&
          accountAddressHex == other.accountAddressHex;
}

class DerivedAccountDataResponse {
  final DerivedAccountData? value;
  final String? error;

  const DerivedAccountDataResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DerivedAccountDataResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class I64Response {
  final PlatformInt64? value;
  final String? error;

  const I64Response({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is I64Response &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class StarknetSignatureData {
  final String rHex;
  final String sHex;

  const StarknetSignatureData({
    required this.rHex,
    required this.sHex,
  });

  @override
  int get hashCode => rHex.hashCode ^ sHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarknetSignatureData &&
          runtimeType == other.runtimeType &&
          rHex == other.rHex &&
          sHex == other.sHex;
}

class StarknetSignatureDataResponse {
  final StarknetSignatureData? value;
  final String? error;

  const StarknetSignatureDataResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarknetSignatureDataResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class StringResponse {
  final String? value;
  final String? error;

  const StringResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class TransferHistoryItem {
  final String transactionHash;
  final PlatformInt64? blockNumber;
  final String from;
  final String to;
  final String amountWei;
  final bool isOutgoing;
  final String tokenSymbol;
  final PlatformInt64? blockTimestamp;
  final String? txFeeWei;

  const TransferHistoryItem({
    required this.transactionHash,
    this.blockNumber,
    required this.from,
    required this.to,
    required this.amountWei,
    required this.isOutgoing,
    required this.tokenSymbol,
    this.blockTimestamp,
    this.txFeeWei,
  });

  @override
  int get hashCode =>
      transactionHash.hashCode ^
      blockNumber.hashCode ^
      from.hashCode ^
      to.hashCode ^
      amountWei.hashCode ^
      isOutgoing.hashCode ^
      tokenSymbol.hashCode ^
      blockTimestamp.hashCode ^
      txFeeWei.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferHistoryItem &&
          runtimeType == other.runtimeType &&
          transactionHash == other.transactionHash &&
          blockNumber == other.blockNumber &&
          from == other.from &&
          to == other.to &&
          amountWei == other.amountWei &&
          isOutgoing == other.isOutgoing &&
          tokenSymbol == other.tokenSymbol &&
          blockTimestamp == other.blockTimestamp &&
          txFeeWei == other.txFeeWei;
}

class TransferHistoryResponse {
  final List<TransferHistoryItem> items;
  final String? error;

  const TransferHistoryResponse({
    required this.items,
    this.error,
  });

  @override
  int get hashCode => items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferHistoryResponse &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          error == other.error;
}
