// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `actual_fee_from_receipt`, `adjust_gas_amount`, `adjust_gas_price`, `biguint_to_uint256_words`, `build_deploy_transaction_hash`, `build_execution_calls`, `build_invoke_transaction_hash`, `calculate_overall_fee_from_params`, `call_token_decimals`, `call_token_string`, `derive_account_address_from_public_key`, `derive_account_from_public_key_inner`, `derive_account_inner`, `derive_private_key_from_mnemonic`, `estimate_execute_fee_inner`, `execute_calls_external_signer_inner`, `execute_calls_inner`, `felt_to_biguint`, `felt_to_hex`, `felt_to_short_string`, `fetch_block_timestamp`, `fetch_latest_block_tip`, `fetch_paginated_transfer_events`, `fetch_transaction_fee`, `format_account_error`, `format_provider_error`, `format_starknet_error`, `from_prepared`, `from_result`, `from_result`, `from_result`, `from_result`, `from_result`, `from_result`, `from_result`, `from_result`, `from_result`, `from_result`, `get_typed_data_message_hash_inner`, `is_account_deployed_with_provider`, `make_provider`, `make_single_owner_account`, `normalize_hex`, `parse_chain_id`, `parse_decimal_biguint`, `parse_entrypoint_selector`, `parse_felt_hex`, `parse_private_key`, `parse_signature_hex`, `parse_transfer_event`, `parse_u128_decimal`, `prepare_external_execution_inner`, `prepare_transaction_params_from_estimate_with_tip`, `prepare_transaction_params_from_fee_estimate`, `run_async`, `sign_message_hash_inner`, `sign_typed_data_inner`, `split_result`, `to_prepared`, `transfer_calldata_hex`, `transfer_calldata`, `uint256_from_call_result`, `uint256_from_words`, `validate_derived_account_address`, `validate_private_key`, `verify_message_hash_signature_inner`, `wait_for_transaction`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ExternalSignerError`, `PreparedExternalExecution`, `PreparedTransactionParams`, `PublicKeyOnlySigner`, `SerializedExternalExecutionPlan`, `SerializedPreparedTransactionParams`, `TransferEventRecord`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `get_public_key`, `is_interactive`, `sign_hash`

Future<DerivedAccountDataResponse> deriveAccount(
        {String? mnemonic,
        String? passphrase,
        String? privateKeyHex,
        required String accountClassHashHex}) =>
    RustLib.instance.api.crateApiStarknetDeriveAccount(
        mnemonic: mnemonic,
        passphrase: passphrase,
        privateKeyHex: privateKeyHex,
        accountClassHashHex: accountClassHashHex);

Future<DerivedAccountDataResponse> deriveAccountFromPublicKey(
        {required String publicKeyHex, required String accountClassHashHex}) =>
    RustLib.instance.api.crateApiStarknetDeriveAccountFromPublicKey(
        publicKeyHex: publicKeyHex, accountClassHashHex: accountClassHashHex);

Future<StringResponse> getTokenBalance(
        {required String nodeUrl,
        required String accountAddressHex,
        required String tokenAddressHex}) =>
    RustLib.instance.api.crateApiStarknetGetTokenBalance(
        nodeUrl: nodeUrl,
        accountAddressHex: accountAddressHex,
        tokenAddressHex: tokenAddressHex);

Future<TokenMetadataResponse> getTokenMetadata(
        {required String nodeUrl, required String tokenAddressHex}) =>
    RustLib.instance.api.crateApiStarknetGetTokenMetadata(
        nodeUrl: nodeUrl, tokenAddressHex: tokenAddressHex);

Future<BoolResponse> isAccountDeployed(
        {required String nodeUrl, required String accountAddressHex}) =>
    RustLib.instance.api.crateApiStarknetIsAccountDeployed(
        nodeUrl: nodeUrl, accountAddressHex: accountAddressHex);

Future<StringResponse> estimateTransferFee(
        {required String nodeUrl,
        required String privateKeyHex,
        required String accountAddressHex,
        required String recipientAddressHex,
        required String tokenAddressHex,
        required String amountWei,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetEstimateTransferFee(
        nodeUrl: nodeUrl,
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        recipientAddressHex: recipientAddressHex,
        tokenAddressHex: tokenAddressHex,
        amountWei: amountWei,
        chainIdHex: chainIdHex);

Future<StringResponse> estimateStandardTransferFee(
        {required String nodeUrl,
        required String privateKeyHex,
        required String accountAddressHex,
        required String tokenAddressHex,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetEstimateStandardTransferFee(
        nodeUrl: nodeUrl,
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        tokenAddressHex: tokenAddressHex,
        chainIdHex: chainIdHex);

Future<StringResponse> sendTransfer(
        {required String nodeUrl,
        required String privateKeyHex,
        required String accountAddressHex,
        required String recipientAddressHex,
        required String tokenAddressHex,
        required String amountWei,
        required String accountClassHashHex,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetSendTransfer(
        nodeUrl: nodeUrl,
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        recipientAddressHex: recipientAddressHex,
        tokenAddressHex: tokenAddressHex,
        amountWei: amountWei,
        accountClassHashHex: accountClassHashHex,
        chainIdHex: chainIdHex);

Future<FeeQuoteResponse> estimateExecuteFee(
        {required String nodeUrl,
        required String privateKeyHex,
        required String accountAddressHex,
        required String accountClassHashHex,
        required List<StarknetCallInput> calls,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetEstimateExecuteFee(
        nodeUrl: nodeUrl,
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        accountClassHashHex: accountClassHashHex,
        calls: calls,
        chainIdHex: chainIdHex);

Future<FeeQuoteResponse> estimateExecuteFeeExternalSigner(
        {required String nodeUrl,
        required String publicKeyHex,
        required String accountAddressHex,
        required String accountClassHashHex,
        required List<StarknetCallInput> calls,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetEstimateExecuteFeeExternalSigner(
        nodeUrl: nodeUrl,
        publicKeyHex: publicKeyHex,
        accountAddressHex: accountAddressHex,
        accountClassHashHex: accountClassHashHex,
        calls: calls,
        chainIdHex: chainIdHex);

Future<StringResponse> executeCalls(
        {required String nodeUrl,
        required String privateKeyHex,
        required String accountAddressHex,
        required String accountClassHashHex,
        required List<StarknetCallInput> calls,
        String? chainIdHex}) =>
    RustLib.instance.api.crateApiStarknetExecuteCalls(
        nodeUrl: nodeUrl,
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        accountClassHashHex: accountClassHashHex,
        calls: calls,
        chainIdHex: chainIdHex);

Future<ExecutionPlanResponse> getExecuteTransactionHashesExternalSigner(
        {required String nodeUrl,
        required String publicKeyHex,
        required String accountAddressHex,
        required String accountClassHashHex,
        required List<StarknetCallInput> calls,
        String? chainIdHex}) =>
    RustLib.instance.api
        .crateApiStarknetGetExecuteTransactionHashesExternalSigner(
            nodeUrl: nodeUrl,
            publicKeyHex: publicKeyHex,
            accountAddressHex: accountAddressHex,
            accountClassHashHex: accountClassHashHex,
            calls: calls,
            chainIdHex: chainIdHex);

Future<StringResponse> executeCallsExternalSigner(
        {required String nodeUrl,
        required String planJson,
        required String invokeRHex,
        required String invokeSHex,
        String? deployRHex,
        String? deploySHex}) =>
    RustLib.instance.api.crateApiStarknetExecuteCallsExternalSigner(
        nodeUrl: nodeUrl,
        planJson: planJson,
        invokeRHex: invokeRHex,
        invokeSHex: invokeSHex,
        deployRHex: deployRHex,
        deploySHex: deploySHex);

Future<TransferHistoryResponse> fetchTransferHistory(
        {required String nodeUrl,
        required String accountAddressHex,
        required String tokenAddressHex,
        required String tokenSymbol,
        PlatformInt64? fromBlock,
        int? maxPages}) =>
    RustLib.instance.api.crateApiStarknetFetchTransferHistory(
        nodeUrl: nodeUrl,
        accountAddressHex: accountAddressHex,
        tokenAddressHex: tokenAddressHex,
        tokenSymbol: tokenSymbol,
        fromBlock: fromBlock,
        maxPages: maxPages);

Future<I64Response> getBlockNumber({required String nodeUrl}) =>
    RustLib.instance.api.crateApiStarknetGetBlockNumber(nodeUrl: nodeUrl);

Future<StarknetSignatureDataResponse> signMessageHash(
        {required String privateKeyHex, required String messageHashHex}) =>
    RustLib.instance.api.crateApiStarknetSignMessageHash(
        privateKeyHex: privateKeyHex, messageHashHex: messageHashHex);

Future<BoolResponse> verifyMessageHashSignature(
        {required String publicKeyHex,
        required String messageHashHex,
        required String rHex,
        required String sHex}) =>
    RustLib.instance.api.crateApiStarknetVerifyMessageHashSignature(
        publicKeyHex: publicKeyHex,
        messageHashHex: messageHashHex,
        rHex: rHex,
        sHex: sHex);

Future<StringListResponse> signTypedData(
        {required String privateKeyHex,
        required String accountAddressHex,
        required String typedDataJson}) =>
    RustLib.instance.api.crateApiStarknetSignTypedData(
        privateKeyHex: privateKeyHex,
        accountAddressHex: accountAddressHex,
        typedDataJson: typedDataJson);

Future<StringResponse> getTypedDataMessageHash(
        {required String accountAddressHex, required String typedDataJson}) =>
    RustLib.instance.api.crateApiStarknetGetTypedDataMessageHash(
        accountAddressHex: accountAddressHex, typedDataJson: typedDataJson);

class BoolResponse {
  final bool? value;
  final String? error;

  const BoolResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoolResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class DerivedAccountData {
  final String privateKeyHex;
  final String publicKeyHex;
  final String accountAddressHex;

  const DerivedAccountData({
    required this.privateKeyHex,
    required this.publicKeyHex,
    required this.accountAddressHex,
  });

  @override
  int get hashCode =>
      privateKeyHex.hashCode ^
      publicKeyHex.hashCode ^
      accountAddressHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DerivedAccountData &&
          runtimeType == other.runtimeType &&
          privateKeyHex == other.privateKeyHex &&
          publicKeyHex == other.publicKeyHex &&
          accountAddressHex == other.accountAddressHex;
}

class DerivedAccountDataResponse {
  final DerivedAccountData? value;
  final String? error;

  const DerivedAccountDataResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DerivedAccountDataResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class ExecutionPlanResponse {
  final StarknetExecutionPlanData? value;
  final String? error;

  const ExecutionPlanResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecutionPlanResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class FeeQuoteResponse {
  final StarknetFeeQuote? value;
  final String? error;

  const FeeQuoteResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeeQuoteResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class I64Response {
  final PlatformInt64? value;
  final String? error;

  const I64Response({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is I64Response &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class StarknetCallInput {
  final String contractAddressHex;
  final String entrypoint;
  final List<String> calldataHex;

  const StarknetCallInput({
    required this.contractAddressHex,
    required this.entrypoint,
    required this.calldataHex,
  });

  @override
  int get hashCode =>
      contractAddressHex.hashCode ^ entrypoint.hashCode ^ calldataHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarknetCallInput &&
          runtimeType == other.runtimeType &&
          contractAddressHex == other.contractAddressHex &&
          entrypoint == other.entrypoint &&
          calldataHex == other.calldataHex;
}

class StarknetExecutionPlanData {
  final String invokeTransactionHashHex;
  final String? deployAccountTransactionHashHex;
  final bool accountDeploymentRequired;
  final String planJson;

  const StarknetExecutionPlanData({
    required this.invokeTransactionHashHex,
    this.deployAccountTransactionHashHex,
    required this.accountDeploymentRequired,
    required this.planJson,
  });

  @override
  int get hashCode =>
      invokeTransactionHashHex.hashCode ^
      deployAccountTransactionHashHex.hashCode ^
      accountDeploymentRequired.hashCode ^
      planJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarknetExecutionPlanData &&
          runtimeType == other.runtimeType &&
          invokeTransactionHashHex == other.invokeTransactionHashHex &&
          deployAccountTransactionHashHex ==
              other.deployAccountTransactionHashHex &&
          accountDeploymentRequired == other.accountDeploymentRequired &&
          planJson == other.planJson;
}

class StarknetFeeQuote {
  final String overallFeeWei;
  final String executionFeeWei;
  final String? deployAccountFeeWei;
  final bool accountDeploymentRequired;

  const StarknetFeeQuote({
    required this.overallFeeWei,
    required this.executionFeeWei,
    this.deployAccountFeeWei,
    required this.accountDeploymentRequired,
  });

  @override
  int get hashCode =>
      overallFeeWei.hashCode ^
      executionFeeWei.hashCode ^
      deployAccountFeeWei.hashCode ^
      accountDeploymentRequired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarknetFeeQuote &&
          runtimeType == other.runtimeType &&
          overallFeeWei == other.overallFeeWei &&
          executionFeeWei == other.executionFeeWei &&
          deployAccountFeeWei == other.deployAccountFeeWei &&
          accountDeploymentRequired == other.accountDeploymentRequired;
}

class StarknetSignatureData {
  final String rHex;
  final String sHex;

  const StarknetSignatureData({
    required this.rHex,
    required this.sHex,
  });

  @override
  int get hashCode => rHex.hashCode ^ sHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarknetSignatureData &&
          runtimeType == other.runtimeType &&
          rHex == other.rHex &&
          sHex == other.sHex;
}

class StarknetSignatureDataResponse {
  final StarknetSignatureData? value;
  final String? error;

  const StarknetSignatureDataResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarknetSignatureDataResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class StarknetTokenMetadata {
  final String tokenAddressHex;
  final String name;
  final String symbol;
  final int decimals;

  const StarknetTokenMetadata({
    required this.tokenAddressHex,
    required this.name,
    required this.symbol,
    required this.decimals,
  });

  @override
  int get hashCode =>
      tokenAddressHex.hashCode ^
      name.hashCode ^
      symbol.hashCode ^
      decimals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarknetTokenMetadata &&
          runtimeType == other.runtimeType &&
          tokenAddressHex == other.tokenAddressHex &&
          name == other.name &&
          symbol == other.symbol &&
          decimals == other.decimals;
}

class StringListResponse {
  final List<String> items;
  final String? error;

  const StringListResponse({
    required this.items,
    this.error,
  });

  @override
  int get hashCode => items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringListResponse &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          error == other.error;
}

class StringResponse {
  final String? value;
  final String? error;

  const StringResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class TokenMetadataResponse {
  final StarknetTokenMetadata? value;
  final String? error;

  const TokenMetadataResponse({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenMetadataResponse &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

class TransferHistoryItem {
  final String transactionHash;
  final String eventId;
  final PlatformInt64 eventIndex;
  final PlatformInt64? blockNumber;
  final String from;
  final String to;
  final String amountWei;
  final bool isOutgoing;
  final String tokenSymbol;
  final String tokenAddressHex;
  final PlatformInt64? blockTimestamp;
  final String? txFeeWei;

  const TransferHistoryItem({
    required this.transactionHash,
    required this.eventId,
    required this.eventIndex,
    this.blockNumber,
    required this.from,
    required this.to,
    required this.amountWei,
    required this.isOutgoing,
    required this.tokenSymbol,
    required this.tokenAddressHex,
    this.blockTimestamp,
    this.txFeeWei,
  });

  @override
  int get hashCode =>
      transactionHash.hashCode ^
      eventId.hashCode ^
      eventIndex.hashCode ^
      blockNumber.hashCode ^
      from.hashCode ^
      to.hashCode ^
      amountWei.hashCode ^
      isOutgoing.hashCode ^
      tokenSymbol.hashCode ^
      tokenAddressHex.hashCode ^
      blockTimestamp.hashCode ^
      txFeeWei.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferHistoryItem &&
          runtimeType == other.runtimeType &&
          transactionHash == other.transactionHash &&
          eventId == other.eventId &&
          eventIndex == other.eventIndex &&
          blockNumber == other.blockNumber &&
          from == other.from &&
          to == other.to &&
          amountWei == other.amountWei &&
          isOutgoing == other.isOutgoing &&
          tokenSymbol == other.tokenSymbol &&
          tokenAddressHex == other.tokenAddressHex &&
          blockTimestamp == other.blockTimestamp &&
          txFeeWei == other.txFeeWei;
}

class TransferHistoryResponse {
  final List<TransferHistoryItem> items;
  final String? error;

  const TransferHistoryResponse({
    required this.items,
    this.error,
  });

  @override
  int get hashCode => items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferHistoryResponse &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          error == other.error;
}
