// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/starknet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiStarknetInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1087241512;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'cw_starknet_rust',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<DerivedAccountDataResponse> crateApiStarknetDeriveAccount(
      {String? mnemonic,
      String? passphrase,
      String? privateKeyHex,
      required String accountClassHashHex});

  Future<DerivedAccountDataResponse> crateApiStarknetDeriveAccountFromPublicKey(
      {required String publicKeyHex, required String accountClassHashHex});

  Future<FeeQuoteResponse> crateApiStarknetEstimateExecuteFee(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String accountClassHashHex,
      required List<StarknetCallInput> calls,
      String? chainIdHex});

  Future<FeeQuoteResponse> crateApiStarknetEstimateExecuteFeeExternalSigner(
      {required String nodeUrl,
      required String publicKeyHex,
      required String accountAddressHex,
      required String accountClassHashHex,
      required List<StarknetCallInput> calls,
      String? chainIdHex});

  Future<StringResponse> crateApiStarknetEstimateStandardTransferFee(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String tokenAddressHex,
      String? chainIdHex});

  Future<StringResponse> crateApiStarknetEstimateTransferFee(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String recipientAddressHex,
      required String tokenAddressHex,
      required String amountWei,
      String? chainIdHex});

  Future<StringResponse> crateApiStarknetExecuteCalls(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String accountClassHashHex,
      required List<StarknetCallInput> calls,
      String? chainIdHex});

  Future<StringResponse> crateApiStarknetExecuteCallsExternalSigner(
      {required String nodeUrl,
      required String planJson,
      required String invokeRHex,
      required String invokeSHex,
      String? deployRHex,
      String? deploySHex});

  Future<TransferHistoryResponse> crateApiStarknetFetchTransferHistory(
      {required String nodeUrl,
      required String accountAddressHex,
      required String tokenAddressHex,
      required String tokenSymbol,
      PlatformInt64? fromBlock,
      int? maxPages});

  Future<I64Response> crateApiStarknetGetBlockNumber({required String nodeUrl});

  Future<ExecutionPlanResponse>
      crateApiStarknetGetExecuteTransactionHashesExternalSigner(
          {required String nodeUrl,
          required String publicKeyHex,
          required String accountAddressHex,
          required String accountClassHashHex,
          required List<StarknetCallInput> calls,
          String? chainIdHex});

  Future<StringResponse> crateApiStarknetGetTokenBalance(
      {required String nodeUrl,
      required String accountAddressHex,
      required String tokenAddressHex});

  Future<TokenMetadataResponse> crateApiStarknetGetTokenMetadata(
      {required String nodeUrl, required String tokenAddressHex});

  Future<StringResponse> crateApiStarknetGetTypedDataMessageHash(
      {required String accountAddressHex, required String typedDataJson});

  Future<void> crateApiStarknetInitApp();

  Future<BoolResponse> crateApiStarknetIsAccountDeployed(
      {required String nodeUrl, required String accountAddressHex});

  Future<StringResponse> crateApiStarknetSendTransfer(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String recipientAddressHex,
      required String tokenAddressHex,
      required String amountWei,
      required String accountClassHashHex,
      String? chainIdHex});

  Future<StarknetSignatureDataResponse> crateApiStarknetSignMessageHash(
      {required String privateKeyHex, required String messageHashHex});

  Future<StringListResponse> crateApiStarknetSignTypedData(
      {required String privateKeyHex,
      required String accountAddressHex,
      required String typedDataJson});

  Future<BoolResponse> crateApiStarknetVerifyMessageHashSignature(
      {required String publicKeyHex,
      required String messageHashHex,
      required String rHex,
      required String sHex});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<DerivedAccountDataResponse> crateApiStarknetDeriveAccount(
      {String? mnemonic,
      String? passphrase,
      String? privateKeyHex,
      required String accountClassHashHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(mnemonic, serializer);
        sse_encode_opt_String(passphrase, serializer);
        sse_encode_opt_String(privateKeyHex, serializer);
        sse_encode_String(accountClassHashHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_derived_account_data_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetDeriveAccountConstMeta,
      argValues: [mnemonic, passphrase, privateKeyHex, accountClassHashHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetDeriveAccountConstMeta =>
      const TaskConstMeta(
        debugName: "derive_account",
        argNames: [
          "mnemonic",
          "passphrase",
          "privateKeyHex",
          "accountClassHashHex"
        ],
      );

  @override
  Future<DerivedAccountDataResponse> crateApiStarknetDeriveAccountFromPublicKey(
      {required String publicKeyHex, required String accountClassHashHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(publicKeyHex, serializer);
        sse_encode_String(accountClassHashHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_derived_account_data_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetDeriveAccountFromPublicKeyConstMeta,
      argValues: [publicKeyHex, accountClassHashHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetDeriveAccountFromPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "derive_account_from_public_key",
        argNames: ["publicKeyHex", "accountClassHashHex"],
      );

  @override
  Future<FeeQuoteResponse> crateApiStarknetEstimateExecuteFee(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String accountClassHashHex,
      required List<StarknetCallInput> calls,
      String? chainIdHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(accountClassHashHex, serializer);
        sse_encode_list_starknet_call_input(calls, serializer);
        sse_encode_opt_String(chainIdHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_fee_quote_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetEstimateExecuteFeeConstMeta,
      argValues: [
        nodeUrl,
        privateKeyHex,
        accountAddressHex,
        accountClassHashHex,
        calls,
        chainIdHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetEstimateExecuteFeeConstMeta =>
      const TaskConstMeta(
        debugName: "estimate_execute_fee",
        argNames: [
          "nodeUrl",
          "privateKeyHex",
          "accountAddressHex",
          "accountClassHashHex",
          "calls",
          "chainIdHex"
        ],
      );

  @override
  Future<FeeQuoteResponse> crateApiStarknetEstimateExecuteFeeExternalSigner(
      {required String nodeUrl,
      required String publicKeyHex,
      required String accountAddressHex,
      required String accountClassHashHex,
      required List<StarknetCallInput> calls,
      String? chainIdHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(publicKeyHex, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(accountClassHashHex, serializer);
        sse_encode_list_starknet_call_input(calls, serializer);
        sse_encode_opt_String(chainIdHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_fee_quote_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetEstimateExecuteFeeExternalSignerConstMeta,
      argValues: [
        nodeUrl,
        publicKeyHex,
        accountAddressHex,
        accountClassHashHex,
        calls,
        chainIdHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiStarknetEstimateExecuteFeeExternalSignerConstMeta =>
          const TaskConstMeta(
            debugName: "estimate_execute_fee_external_signer",
            argNames: [
              "nodeUrl",
              "publicKeyHex",
              "accountAddressHex",
              "accountClassHashHex",
              "calls",
              "chainIdHex"
            ],
          );

  @override
  Future<StringResponse> crateApiStarknetEstimateStandardTransferFee(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String tokenAddressHex,
      String? chainIdHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(tokenAddressHex, serializer);
        sse_encode_opt_String(chainIdHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_string_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetEstimateStandardTransferFeeConstMeta,
      argValues: [
        nodeUrl,
        privateKeyHex,
        accountAddressHex,
        tokenAddressHex,
        chainIdHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetEstimateStandardTransferFeeConstMeta =>
      const TaskConstMeta(
        debugName: "estimate_standard_transfer_fee",
        argNames: [
          "nodeUrl",
          "privateKeyHex",
          "accountAddressHex",
          "tokenAddressHex",
          "chainIdHex"
        ],
      );

  @override
  Future<StringResponse> crateApiStarknetEstimateTransferFee(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String recipientAddressHex,
      required String tokenAddressHex,
      required String amountWei,
      String? chainIdHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(recipientAddressHex, serializer);
        sse_encode_String(tokenAddressHex, serializer);
        sse_encode_String(amountWei, serializer);
        sse_encode_opt_String(chainIdHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_string_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetEstimateTransferFeeConstMeta,
      argValues: [
        nodeUrl,
        privateKeyHex,
        accountAddressHex,
        recipientAddressHex,
        tokenAddressHex,
        amountWei,
        chainIdHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetEstimateTransferFeeConstMeta =>
      const TaskConstMeta(
        debugName: "estimate_transfer_fee",
        argNames: [
          "nodeUrl",
          "privateKeyHex",
          "accountAddressHex",
          "recipientAddressHex",
          "tokenAddressHex",
          "amountWei",
          "chainIdHex"
        ],
      );

  @override
  Future<StringResponse> crateApiStarknetExecuteCalls(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String accountClassHashHex,
      required List<StarknetCallInput> calls,
      String? chainIdHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(accountClassHashHex, serializer);
        sse_encode_list_starknet_call_input(calls, serializer);
        sse_encode_opt_String(chainIdHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_string_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetExecuteCallsConstMeta,
      argValues: [
        nodeUrl,
        privateKeyHex,
        accountAddressHex,
        accountClassHashHex,
        calls,
        chainIdHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetExecuteCallsConstMeta =>
      const TaskConstMeta(
        debugName: "execute_calls",
        argNames: [
          "nodeUrl",
          "privateKeyHex",
          "accountAddressHex",
          "accountClassHashHex",
          "calls",
          "chainIdHex"
        ],
      );

  @override
  Future<StringResponse> crateApiStarknetExecuteCallsExternalSigner(
      {required String nodeUrl,
      required String planJson,
      required String invokeRHex,
      required String invokeSHex,
      String? deployRHex,
      String? deploySHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(planJson, serializer);
        sse_encode_String(invokeRHex, serializer);
        sse_encode_String(invokeSHex, serializer);
        sse_encode_opt_String(deployRHex, serializer);
        sse_encode_opt_String(deploySHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_string_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetExecuteCallsExternalSignerConstMeta,
      argValues: [
        nodeUrl,
        planJson,
        invokeRHex,
        invokeSHex,
        deployRHex,
        deploySHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetExecuteCallsExternalSignerConstMeta =>
      const TaskConstMeta(
        debugName: "execute_calls_external_signer",
        argNames: [
          "nodeUrl",
          "planJson",
          "invokeRHex",
          "invokeSHex",
          "deployRHex",
          "deploySHex"
        ],
      );

  @override
  Future<TransferHistoryResponse> crateApiStarknetFetchTransferHistory(
      {required String nodeUrl,
      required String accountAddressHex,
      required String tokenAddressHex,
      required String tokenSymbol,
      PlatformInt64? fromBlock,
      int? maxPages}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(tokenAddressHex, serializer);
        sse_encode_String(tokenSymbol, serializer);
        sse_encode_opt_box_autoadd_i_64(fromBlock, serializer);
        sse_encode_opt_box_autoadd_i_32(maxPages, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_transfer_history_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetFetchTransferHistoryConstMeta,
      argValues: [
        nodeUrl,
        accountAddressHex,
        tokenAddressHex,
        tokenSymbol,
        fromBlock,
        maxPages
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetFetchTransferHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_transfer_history",
        argNames: [
          "nodeUrl",
          "accountAddressHex",
          "tokenAddressHex",
          "tokenSymbol",
          "fromBlock",
          "maxPages"
        ],
      );

  @override
  Future<I64Response> crateApiStarknetGetBlockNumber(
      {required String nodeUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_64_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetGetBlockNumberConstMeta,
      argValues: [nodeUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetGetBlockNumberConstMeta =>
      const TaskConstMeta(
        debugName: "get_block_number",
        argNames: ["nodeUrl"],
      );

  @override
  Future<ExecutionPlanResponse>
      crateApiStarknetGetExecuteTransactionHashesExternalSigner(
          {required String nodeUrl,
          required String publicKeyHex,
          required String accountAddressHex,
          required String accountClassHashHex,
          required List<StarknetCallInput> calls,
          String? chainIdHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(publicKeyHex, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(accountClassHashHex, serializer);
        sse_encode_list_starknet_call_input(calls, serializer);
        sse_encode_opt_String(chainIdHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_execution_plan_response,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiStarknetGetExecuteTransactionHashesExternalSignerConstMeta,
      argValues: [
        nodeUrl,
        publicKeyHex,
        accountAddressHex,
        accountClassHashHex,
        calls,
        chainIdHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiStarknetGetExecuteTransactionHashesExternalSignerConstMeta =>
          const TaskConstMeta(
            debugName: "get_execute_transaction_hashes_external_signer",
            argNames: [
              "nodeUrl",
              "publicKeyHex",
              "accountAddressHex",
              "accountClassHashHex",
              "calls",
              "chainIdHex"
            ],
          );

  @override
  Future<StringResponse> crateApiStarknetGetTokenBalance(
      {required String nodeUrl,
      required String accountAddressHex,
      required String tokenAddressHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(tokenAddressHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_string_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetGetTokenBalanceConstMeta,
      argValues: [nodeUrl, accountAddressHex, tokenAddressHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetGetTokenBalanceConstMeta =>
      const TaskConstMeta(
        debugName: "get_token_balance",
        argNames: ["nodeUrl", "accountAddressHex", "tokenAddressHex"],
      );

  @override
  Future<TokenMetadataResponse> crateApiStarknetGetTokenMetadata(
      {required String nodeUrl, required String tokenAddressHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(tokenAddressHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_token_metadata_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetGetTokenMetadataConstMeta,
      argValues: [nodeUrl, tokenAddressHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetGetTokenMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "get_token_metadata",
        argNames: ["nodeUrl", "tokenAddressHex"],
      );

  @override
  Future<StringResponse> crateApiStarknetGetTypedDataMessageHash(
      {required String accountAddressHex, required String typedDataJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(typedDataJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_string_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetGetTypedDataMessageHashConstMeta,
      argValues: [accountAddressHex, typedDataJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetGetTypedDataMessageHashConstMeta =>
      const TaskConstMeta(
        debugName: "get_typed_data_message_hash",
        argNames: ["accountAddressHex", "typedDataJson"],
      );

  @override
  Future<void> crateApiStarknetInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<BoolResponse> crateApiStarknetIsAccountDeployed(
      {required String nodeUrl, required String accountAddressHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(accountAddressHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetIsAccountDeployedConstMeta,
      argValues: [nodeUrl, accountAddressHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetIsAccountDeployedConstMeta =>
      const TaskConstMeta(
        debugName: "is_account_deployed",
        argNames: ["nodeUrl", "accountAddressHex"],
      );

  @override
  Future<StringResponse> crateApiStarknetSendTransfer(
      {required String nodeUrl,
      required String privateKeyHex,
      required String accountAddressHex,
      required String recipientAddressHex,
      required String tokenAddressHex,
      required String amountWei,
      required String accountClassHashHex,
      String? chainIdHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeUrl, serializer);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(recipientAddressHex, serializer);
        sse_encode_String(tokenAddressHex, serializer);
        sse_encode_String(amountWei, serializer);
        sse_encode_String(accountClassHashHex, serializer);
        sse_encode_opt_String(chainIdHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_string_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetSendTransferConstMeta,
      argValues: [
        nodeUrl,
        privateKeyHex,
        accountAddressHex,
        recipientAddressHex,
        tokenAddressHex,
        amountWei,
        accountClassHashHex,
        chainIdHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetSendTransferConstMeta =>
      const TaskConstMeta(
        debugName: "send_transfer",
        argNames: [
          "nodeUrl",
          "privateKeyHex",
          "accountAddressHex",
          "recipientAddressHex",
          "tokenAddressHex",
          "amountWei",
          "accountClassHashHex",
          "chainIdHex"
        ],
      );

  @override
  Future<StarknetSignatureDataResponse> crateApiStarknetSignMessageHash(
      {required String privateKeyHex, required String messageHashHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(messageHashHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_starknet_signature_data_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetSignMessageHashConstMeta,
      argValues: [privateKeyHex, messageHashHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetSignMessageHashConstMeta =>
      const TaskConstMeta(
        debugName: "sign_message_hash",
        argNames: ["privateKeyHex", "messageHashHex"],
      );

  @override
  Future<StringListResponse> crateApiStarknetSignTypedData(
      {required String privateKeyHex,
      required String accountAddressHex,
      required String typedDataJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(accountAddressHex, serializer);
        sse_encode_String(typedDataJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_string_list_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetSignTypedDataConstMeta,
      argValues: [privateKeyHex, accountAddressHex, typedDataJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetSignTypedDataConstMeta =>
      const TaskConstMeta(
        debugName: "sign_typed_data",
        argNames: ["privateKeyHex", "accountAddressHex", "typedDataJson"],
      );

  @override
  Future<BoolResponse> crateApiStarknetVerifyMessageHashSignature(
      {required String publicKeyHex,
      required String messageHashHex,
      required String rHex,
      required String sHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(publicKeyHex, serializer);
        sse_encode_String(messageHashHex, serializer);
        sse_encode_String(rHex, serializer);
        sse_encode_String(sHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool_response,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStarknetVerifyMessageHashSignatureConstMeta,
      argValues: [publicKeyHex, messageHashHex, rHex, sHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStarknetVerifyMessageHashSignatureConstMeta =>
      const TaskConstMeta(
        debugName: "verify_message_hash_signature",
        argNames: ["publicKeyHex", "messageHashHex", "rHex", "sHex"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BoolResponse dco_decode_bool_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BoolResponse(
      value: dco_decode_opt_box_autoadd_bool(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DerivedAccountData dco_decode_box_autoadd_derived_account_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_derived_account_data(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  StarknetExecutionPlanData dco_decode_box_autoadd_starknet_execution_plan_data(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_starknet_execution_plan_data(raw);
  }

  @protected
  StarknetFeeQuote dco_decode_box_autoadd_starknet_fee_quote(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_starknet_fee_quote(raw);
  }

  @protected
  StarknetSignatureData dco_decode_box_autoadd_starknet_signature_data(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_starknet_signature_data(raw);
  }

  @protected
  StarknetTokenMetadata dco_decode_box_autoadd_starknet_token_metadata(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_starknet_token_metadata(raw);
  }

  @protected
  DerivedAccountData dco_decode_derived_account_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DerivedAccountData(
      privateKeyHex: dco_decode_String(arr[0]),
      publicKeyHex: dco_decode_String(arr[1]),
      accountAddressHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  DerivedAccountDataResponse dco_decode_derived_account_data_response(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DerivedAccountDataResponse(
      value: dco_decode_opt_box_autoadd_derived_account_data(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  ExecutionPlanResponse dco_decode_execution_plan_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExecutionPlanResponse(
      value: dco_decode_opt_box_autoadd_starknet_execution_plan_data(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  FeeQuoteResponse dco_decode_fee_quote_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FeeQuoteResponse(
      value: dco_decode_opt_box_autoadd_starknet_fee_quote(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  I64Response dco_decode_i_64_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return I64Response(
      value: dco_decode_opt_box_autoadd_i_64(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StarknetCallInput> dco_decode_list_starknet_call_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_starknet_call_input).toList();
  }

  @protected
  List<TransferHistoryItem> dco_decode_list_transfer_history_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_transfer_history_item)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  DerivedAccountData? dco_decode_opt_box_autoadd_derived_account_data(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_derived_account_data(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  StarknetExecutionPlanData?
      dco_decode_opt_box_autoadd_starknet_execution_plan_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_starknet_execution_plan_data(raw);
  }

  @protected
  StarknetFeeQuote? dco_decode_opt_box_autoadd_starknet_fee_quote(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_starknet_fee_quote(raw);
  }

  @protected
  StarknetSignatureData? dco_decode_opt_box_autoadd_starknet_signature_data(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_starknet_signature_data(raw);
  }

  @protected
  StarknetTokenMetadata? dco_decode_opt_box_autoadd_starknet_token_metadata(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_starknet_token_metadata(raw);
  }

  @protected
  StarknetCallInput dco_decode_starknet_call_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StarknetCallInput(
      contractAddressHex: dco_decode_String(arr[0]),
      entrypoint: dco_decode_String(arr[1]),
      calldataHex: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  StarknetExecutionPlanData dco_decode_starknet_execution_plan_data(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StarknetExecutionPlanData(
      invokeTransactionHashHex: dco_decode_String(arr[0]),
      deployAccountTransactionHashHex: dco_decode_opt_String(arr[1]),
      accountDeploymentRequired: dco_decode_bool(arr[2]),
      planJson: dco_decode_String(arr[3]),
    );
  }

  @protected
  StarknetFeeQuote dco_decode_starknet_fee_quote(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StarknetFeeQuote(
      overallFeeWei: dco_decode_String(arr[0]),
      executionFeeWei: dco_decode_String(arr[1]),
      deployAccountFeeWei: dco_decode_opt_String(arr[2]),
      accountDeploymentRequired: dco_decode_bool(arr[3]),
    );
  }

  @protected
  StarknetSignatureData dco_decode_starknet_signature_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StarknetSignatureData(
      rHex: dco_decode_String(arr[0]),
      sHex: dco_decode_String(arr[1]),
    );
  }

  @protected
  StarknetSignatureDataResponse dco_decode_starknet_signature_data_response(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StarknetSignatureDataResponse(
      value: dco_decode_opt_box_autoadd_starknet_signature_data(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  StarknetTokenMetadata dco_decode_starknet_token_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StarknetTokenMetadata(
      tokenAddressHex: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      symbol: dco_decode_String(arr[2]),
      decimals: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  StringListResponse dco_decode_string_list_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StringListResponse(
      items: dco_decode_list_String(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  StringResponse dco_decode_string_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StringResponse(
      value: dco_decode_opt_String(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  TokenMetadataResponse dco_decode_token_metadata_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TokenMetadataResponse(
      value: dco_decode_opt_box_autoadd_starknet_token_metadata(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  TransferHistoryItem dco_decode_transfer_history_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return TransferHistoryItem(
      transactionHash: dco_decode_String(arr[0]),
      eventId: dco_decode_String(arr[1]),
      eventIndex: dco_decode_i_64(arr[2]),
      blockNumber: dco_decode_opt_box_autoadd_i_64(arr[3]),
      from: dco_decode_String(arr[4]),
      to: dco_decode_String(arr[5]),
      amountWei: dco_decode_String(arr[6]),
      isOutgoing: dco_decode_bool(arr[7]),
      tokenSymbol: dco_decode_String(arr[8]),
      tokenAddressHex: dco_decode_String(arr[9]),
      blockTimestamp: dco_decode_opt_box_autoadd_i_64(arr[10]),
      txFeeWei: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  TransferHistoryResponse dco_decode_transfer_history_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TransferHistoryResponse(
      items: dco_decode_list_transfer_history_item(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BoolResponse sse_decode_bool_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return BoolResponse(value: var_value, error: var_error);
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  DerivedAccountData sse_decode_box_autoadd_derived_account_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_derived_account_data(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  StarknetExecutionPlanData sse_decode_box_autoadd_starknet_execution_plan_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_starknet_execution_plan_data(deserializer));
  }

  @protected
  StarknetFeeQuote sse_decode_box_autoadd_starknet_fee_quote(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_starknet_fee_quote(deserializer));
  }

  @protected
  StarknetSignatureData sse_decode_box_autoadd_starknet_signature_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_starknet_signature_data(deserializer));
  }

  @protected
  StarknetTokenMetadata sse_decode_box_autoadd_starknet_token_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_starknet_token_metadata(deserializer));
  }

  @protected
  DerivedAccountData sse_decode_derived_account_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateKeyHex = sse_decode_String(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    var var_accountAddressHex = sse_decode_String(deserializer);
    return DerivedAccountData(
        privateKeyHex: var_privateKeyHex,
        publicKeyHex: var_publicKeyHex,
        accountAddressHex: var_accountAddressHex);
  }

  @protected
  DerivedAccountDataResponse sse_decode_derived_account_data_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value =
        sse_decode_opt_box_autoadd_derived_account_data(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return DerivedAccountDataResponse(value: var_value, error: var_error);
  }

  @protected
  ExecutionPlanResponse sse_decode_execution_plan_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value =
        sse_decode_opt_box_autoadd_starknet_execution_plan_data(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ExecutionPlanResponse(value: var_value, error: var_error);
  }

  @protected
  FeeQuoteResponse sse_decode_fee_quote_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_opt_box_autoadd_starknet_fee_quote(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return FeeQuoteResponse(value: var_value, error: var_error);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  I64Response sse_decode_i_64_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return I64Response(value: var_value, error: var_error);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StarknetCallInput> sse_decode_list_starknet_call_input(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StarknetCallInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_starknet_call_input(deserializer));
    }
    return ans_;
  }

  @protected
  List<TransferHistoryItem> sse_decode_list_transfer_history_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TransferHistoryItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transfer_history_item(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DerivedAccountData? sse_decode_opt_box_autoadd_derived_account_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_derived_account_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StarknetExecutionPlanData?
      sse_decode_opt_box_autoadd_starknet_execution_plan_data(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_starknet_execution_plan_data(
          deserializer));
    } else {
      return null;
    }
  }

  @protected
  StarknetFeeQuote? sse_decode_opt_box_autoadd_starknet_fee_quote(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_starknet_fee_quote(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StarknetSignatureData? sse_decode_opt_box_autoadd_starknet_signature_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_starknet_signature_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StarknetTokenMetadata? sse_decode_opt_box_autoadd_starknet_token_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_starknet_token_metadata(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StarknetCallInput sse_decode_starknet_call_input(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_contractAddressHex = sse_decode_String(deserializer);
    var var_entrypoint = sse_decode_String(deserializer);
    var var_calldataHex = sse_decode_list_String(deserializer);
    return StarknetCallInput(
        contractAddressHex: var_contractAddressHex,
        entrypoint: var_entrypoint,
        calldataHex: var_calldataHex);
  }

  @protected
  StarknetExecutionPlanData sse_decode_starknet_execution_plan_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_invokeTransactionHashHex = sse_decode_String(deserializer);
    var var_deployAccountTransactionHashHex =
        sse_decode_opt_String(deserializer);
    var var_accountDeploymentRequired = sse_decode_bool(deserializer);
    var var_planJson = sse_decode_String(deserializer);
    return StarknetExecutionPlanData(
        invokeTransactionHashHex: var_invokeTransactionHashHex,
        deployAccountTransactionHashHex: var_deployAccountTransactionHashHex,
        accountDeploymentRequired: var_accountDeploymentRequired,
        planJson: var_planJson);
  }

  @protected
  StarknetFeeQuote sse_decode_starknet_fee_quote(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_overallFeeWei = sse_decode_String(deserializer);
    var var_executionFeeWei = sse_decode_String(deserializer);
    var var_deployAccountFeeWei = sse_decode_opt_String(deserializer);
    var var_accountDeploymentRequired = sse_decode_bool(deserializer);
    return StarknetFeeQuote(
        overallFeeWei: var_overallFeeWei,
        executionFeeWei: var_executionFeeWei,
        deployAccountFeeWei: var_deployAccountFeeWei,
        accountDeploymentRequired: var_accountDeploymentRequired);
  }

  @protected
  StarknetSignatureData sse_decode_starknet_signature_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rHex = sse_decode_String(deserializer);
    var var_sHex = sse_decode_String(deserializer);
    return StarknetSignatureData(rHex: var_rHex, sHex: var_sHex);
  }

  @protected
  StarknetSignatureDataResponse sse_decode_starknet_signature_data_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value =
        sse_decode_opt_box_autoadd_starknet_signature_data(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return StarknetSignatureDataResponse(value: var_value, error: var_error);
  }

  @protected
  StarknetTokenMetadata sse_decode_starknet_token_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tokenAddressHex = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_symbol = sse_decode_String(deserializer);
    var var_decimals = sse_decode_i_32(deserializer);
    return StarknetTokenMetadata(
        tokenAddressHex: var_tokenAddressHex,
        name: var_name,
        symbol: var_symbol,
        decimals: var_decimals);
  }

  @protected
  StringListResponse sse_decode_string_list_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return StringListResponse(items: var_items, error: var_error);
  }

  @protected
  StringResponse sse_decode_string_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return StringResponse(value: var_value, error: var_error);
  }

  @protected
  TokenMetadataResponse sse_decode_token_metadata_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value =
        sse_decode_opt_box_autoadd_starknet_token_metadata(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return TokenMetadataResponse(value: var_value, error: var_error);
  }

  @protected
  TransferHistoryItem sse_decode_transfer_history_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transactionHash = sse_decode_String(deserializer);
    var var_eventId = sse_decode_String(deserializer);
    var var_eventIndex = sse_decode_i_64(deserializer);
    var var_blockNumber = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_from = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_amountWei = sse_decode_String(deserializer);
    var var_isOutgoing = sse_decode_bool(deserializer);
    var var_tokenSymbol = sse_decode_String(deserializer);
    var var_tokenAddressHex = sse_decode_String(deserializer);
    var var_blockTimestamp = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_txFeeWei = sse_decode_opt_String(deserializer);
    return TransferHistoryItem(
        transactionHash: var_transactionHash,
        eventId: var_eventId,
        eventIndex: var_eventIndex,
        blockNumber: var_blockNumber,
        from: var_from,
        to: var_to,
        amountWei: var_amountWei,
        isOutgoing: var_isOutgoing,
        tokenSymbol: var_tokenSymbol,
        tokenAddressHex: var_tokenAddressHex,
        blockTimestamp: var_blockTimestamp,
        txFeeWei: var_txFeeWei);
  }

  @protected
  TransferHistoryResponse sse_decode_transfer_history_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_transfer_history_item(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return TransferHistoryResponse(items: var_items, error: var_error);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bool_response(BoolResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_bool(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_derived_account_data(
      DerivedAccountData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_derived_account_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_starknet_execution_plan_data(
      StarknetExecutionPlanData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_starknet_execution_plan_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_starknet_fee_quote(
      StarknetFeeQuote self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_starknet_fee_quote(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_starknet_signature_data(
      StarknetSignatureData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_starknet_signature_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_starknet_token_metadata(
      StarknetTokenMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_starknet_token_metadata(self, serializer);
  }

  @protected
  void sse_encode_derived_account_data(
      DerivedAccountData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.privateKeyHex, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
    sse_encode_String(self.accountAddressHex, serializer);
  }

  @protected
  void sse_encode_derived_account_data_response(
      DerivedAccountDataResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_derived_account_data(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_execution_plan_response(
      ExecutionPlanResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_starknet_execution_plan_data(
        self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_fee_quote_response(
      FeeQuoteResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_starknet_fee_quote(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_i_64_response(I64Response self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_starknet_call_input(
      List<StarknetCallInput> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_starknet_call_input(item, serializer);
    }
  }

  @protected
  void sse_encode_list_transfer_history_item(
      List<TransferHistoryItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transfer_history_item(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_derived_account_data(
      DerivedAccountData? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_derived_account_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_starknet_execution_plan_data(
      StarknetExecutionPlanData? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_starknet_execution_plan_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_starknet_fee_quote(
      StarknetFeeQuote? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_starknet_fee_quote(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_starknet_signature_data(
      StarknetSignatureData? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_starknet_signature_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_starknet_token_metadata(
      StarknetTokenMetadata? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_starknet_token_metadata(self, serializer);
    }
  }

  @protected
  void sse_encode_starknet_call_input(
      StarknetCallInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.contractAddressHex, serializer);
    sse_encode_String(self.entrypoint, serializer);
    sse_encode_list_String(self.calldataHex, serializer);
  }

  @protected
  void sse_encode_starknet_execution_plan_data(
      StarknetExecutionPlanData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.invokeTransactionHashHex, serializer);
    sse_encode_opt_String(self.deployAccountTransactionHashHex, serializer);
    sse_encode_bool(self.accountDeploymentRequired, serializer);
    sse_encode_String(self.planJson, serializer);
  }

  @protected
  void sse_encode_starknet_fee_quote(
      StarknetFeeQuote self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.overallFeeWei, serializer);
    sse_encode_String(self.executionFeeWei, serializer);
    sse_encode_opt_String(self.deployAccountFeeWei, serializer);
    sse_encode_bool(self.accountDeploymentRequired, serializer);
  }

  @protected
  void sse_encode_starknet_signature_data(
      StarknetSignatureData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.rHex, serializer);
    sse_encode_String(self.sHex, serializer);
  }

  @protected
  void sse_encode_starknet_signature_data_response(
      StarknetSignatureDataResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_starknet_signature_data(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_starknet_token_metadata(
      StarknetTokenMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tokenAddressHex, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.symbol, serializer);
    sse_encode_i_32(self.decimals, serializer);
  }

  @protected
  void sse_encode_string_list_response(
      StringListResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.items, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_string_response(
      StringResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_token_metadata_response(
      TokenMetadataResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_starknet_token_metadata(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_transfer_history_item(
      TransferHistoryItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.transactionHash, serializer);
    sse_encode_String(self.eventId, serializer);
    sse_encode_i_64(self.eventIndex, serializer);
    sse_encode_opt_box_autoadd_i_64(self.blockNumber, serializer);
    sse_encode_String(self.from, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_String(self.amountWei, serializer);
    sse_encode_bool(self.isOutgoing, serializer);
    sse_encode_String(self.tokenSymbol, serializer);
    sse_encode_String(self.tokenAddressHex, serializer);
    sse_encode_opt_box_autoadd_i_64(self.blockTimestamp, serializer);
    sse_encode_opt_String(self.txFeeWei, serializer);
  }

  @protected
  void sse_encode_transfer_history_response(
      TransferHistoryResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_transfer_history_item(self.items, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
