ARG BASE_IMAGE
FROM --platform=linux/amd64 ${BASE_IMAGE} AS build

RUN mkdir -p /w/scripts/linux
COPY scripts/prepare_zcash.sh /w/scripts/prepare_zcash.sh
COPY scripts/linux/build_zcash.sh /w/scripts/linux/build_zcash.sh
RUN /w/scripts/linux/build_zcash.sh

FROM --platform=linux/amd64 alpine
COPY --from=build /w /w
