/* PIVX Sapling FFI - Auto-generated by cbindgen */

#ifndef CW_PIVX_SAPLING_H
#define CW_PIVX_SAPLING_H

/* Generated with cbindgen:0.29.0 */

/* Warning: this file was auto-generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Sapling tree depth constant.
 */
#define SAPLING_TREE_DEPTH 32

/**
 * PIVX Sapling activation height.
 */
#define PIVX_SAPLING_ACTIVATION 2700500

/**
 * FFI buffer for returning binary data.
 */
typedef struct FFIBuffer {
  uint8_t *data;
  uintptr_t len;
} FFIBuffer;

/**
 * Derive an address at a specific index.
 */
char *cw_pivx_derive_address(int64_t handle,
                             uint64_t index);

/**
 * Dispose keys.
 */
void cw_pivx_dispose_keys(int64_t handle);

/**
 * Dispose sync engine.
 */
void cw_pivx_dispose_sync_engine(int64_t handle);

/**
 * Estimate transaction fee.
 */
uint64_t cw_pivx_estimate_fee(uintptr_t spends,
                              uintptr_t outputs,
                              uintptr_t t_inputs,
                              uintptr_t t_outputs);

/**
 * Free a buffer allocated by this library.
 */
void cw_pivx_free_buffer(struct FFIBuffer buffer);

/**
 * Free a string allocated by this library.
 */
void cw_pivx_free_string(char *ptr);

/**
 * Get the default payment address.
 */
char *cw_pivx_get_default_address(int64_t handle);

/**
 * Get and clear the last error message.
 */
char *cw_pivx_get_last_error(void);

/**
 * Get the shielded balance.
 */
uint64_t cw_pivx_get_shielded_balance(int64_t handle);

/**
 * Get the current sync height.
 */
uint32_t cw_pivx_get_sync_height(int64_t handle);

/**
 * Get the number of unspent notes.
 */
uintptr_t cw_pivx_get_unspent_note_count(int64_t handle);

/**
 * Get the full viewing key.
 */
char *cw_pivx_get_viewing_key(int64_t handle);

/**
 * Check if proving parameters are available.
 */
uint8_t cw_pivx_has_proving_params(const char *path);

/**
 * Initialize keys from a seed.
 * Returns a handle for future operations, or -1 on error.
 */
int64_t cw_pivx_init_keys(const uint8_t *seed,
                          uintptr_t seed_len,
                          uint8_t is_testnet);

/**
 * Initialize sync engine.
 */
int64_t cw_pivx_init_sync_engine(uint8_t _is_testnet);

/**
 * Reset sync state.
 */
void cw_pivx_reset_sync(int64_t handle);

/**
 * Validate a Sapling address.
 */
uint8_t cw_pivx_validate_address(const char *address,
                                 uint8_t is_testnet);

/**
 * Get the library version.
 */
char *cw_pivx_version(void);

/**
 * Clear the last error.
 */
void pivx_clear_last_error(void);

/**
 * Free a byte buffer allocated by this library.
 *
 * # Safety
 * The pointer must have been allocated by this library and not already freed.
 */
void pivx_free_buffer(unsigned char *ptr,
                      uintptr_t len);

/**
 * Free a string allocated by this library.
 *
 * # Safety
 * The pointer must have been allocated by this library and not already freed.
 */
void pivx_free_string(char *s);

/**
 * Get the last error message.
 * Returns null if no error occurred.
 * Caller must free the returned string with `pivx_free_string`.
 */
char *pivx_get_last_error(void);

int32_t pivx_sapling_create_from_seed(const uint8_t *seed,
                                      uintptr_t seed_len,
                                      int32_t is_testnet,
                                      int32_t *session_id);

int32_t pivx_sapling_destroy(int32_t session_id);

void pivx_sapling_free_string(char *ptr);

int64_t pivx_sapling_get_balance(int32_t session_id);

int32_t pivx_sapling_get_sync_height(int32_t session_id);

int32_t pivx_sapling_init(void);

/**
 * Get the library version string.
 * Caller must free the returned string with `pivx_free_string`.
 */
char *pivx_sapling_version(void);

#endif  /* CW_PIVX_SAPLING_H */
