ARG BASE_IMAGE

FROM --platform=linux/amd64 ${BASE_IMAGE} AS build

COPY scripts/prepare_torch.sh /w/scripts/prepare_torch.sh
COPY scripts/android/build_torch.sh /w/scripts/android/build_torch.sh
RUN /w/scripts/android/build_torch.sh && rm -rf /w/scripts/torch_dart/simplybs

FROM --platform=linux/amd64 alpine
COPY --from=build /w /w
