# yaml-language-server: $schema=../../ffigen.schema.json

name: MWebFlutter
description: Bindings to `go/mweb.h`.
output: 'lib/generated_bindings.g.dart'
headers:
  entry-points:
    - 'android/src/main/jniLibs/arm64-v8a/libmweb.h'
