name: Are translations sane

on: [pull_request]

jobs:
  PR_test_build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Check for translations
        if: github.event_name == 'pull_request'
        run: |
          for i in res/values/strings_*.arb;
          do
            echo "tr: $i"
            cat $i | jq || exit 1
          done
