name: PR Formatting & Lint Check

on: [pull_request]

jobs:
  fast_lint_check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Execute Build and Setup Commands
        run: |
          pushd scripts/android
            source ./app_env.sh cakewallet
            export GITHUB_HUH=yeah
            ./app_config.sh
          popd


      - name: Install dependencies
        run: flutter pub get

      - name: Lint
        run: |
          scripts/lint.sh