name: Cake Wallet Android

on:
  push:
    branches:
      - feat/starknet

permissions:
  contents: read
  packages: write

jobs:
  trusted-branch-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      ref: ${{ github.sha }}
      pr_number: ${{ github.ref_name }}
    secrets: inherit
